### ISSUE TITLE
[UI] Graphic

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#10]
# Graphic
Load icon
![image](https://user-images.githubusercontent.com/9526525/103096600-6cf7df80-463f-11eb-871e-d5683eb6c7ad.png)
## @todo:
- [x] Icon demo
- [x] Support SVG
- [x] Add CSS style
- [x] Support custom CSS style

#### Browsers testing (Laptop/Mobile/Tablet)
- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Opera
- [ ] Edge (only laptop)

#### Device testing
* iPhone 6s Plus, iPad mini, simulator iPhone and iPad
* Maybe will use simulator with Android
---
## Issue report

**Comment by serapath** [comment]
# Icons
Load icon
![image](https://user-images.githubusercontent.com/9526525/103096600-6cf7df80-463f-11eb-871e-d5683eb6c7ad.png)

**Comment by fionataeyang** [comment]
graphic is loaded icon via svg, it is not able to choose any icon form ```datdot-ui-graphic``` .

it is loaded SVG syntax

**Comment by serapath** [comment]
> @ninabreznik 
> [**worklog `2022.04.07` - locking UI elements**](https://youtu.be/X8wpMNnAW2E) 

Notes:
- v.0.0.1-alpha: ui elements, updated to use new comm protocol
- 0.0.0-alpha: ui elements in the original Fiona's state (only a few)


### Results:
**v0.0.1-alpha** (using new comm proto)
- https://github.com/datdot-ui/icon/tree/v0.0.1-alpha

**0.0.0-alpha** (old/Fiona's original)
- https://github.com/datdot-ui/icon/tree/0.0.0-alpha

**Comment by serapath** [comment]
> @ninabreznik 
> [**worklog `2022.04.12` - versioning and documenting components**](https://youtu.be/gCKEtJ2eG8o)

**results:**

- `v0.0.1-alpha`
  - https://github.com/datdot-ui/icon/tree/v0.0.1-alpha
- `v0.0.0-prealpha`
    - https://github.com/datdot-ui/icon/tree/v0.0.0-prealpha
-  `v0.0.0-alpha` 
    - https://github.com/datdot-ui/icon/tree/v0.0.0-alpha 
- updated readme
    - https://github.com/datdot-ui/icon#datdot-ui-icon

**Comment by ninabreznik** [comment]
[[datdot ui worklog] working on v0.0.2-alpha Apr 18, 2022 ]()

**results:**

- `v0.0.2`
  - https://github.com/datdot-ui/icon/tree/v0.0.2
