### ISSUE TITLE
[UI] Plan name

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#103]
# Plan name
![image](https://user-images.githubusercontent.com/9526525/118277998-0abf4e80-b4fc-11eb-9d52-dfd69a3f624f.png)

```js
// datdot-ui-plan-name
require('datdot-ui-label')
require('datdot-ui-input-text')
require('datdot-ui-button')
require('datdot-ui-graphic')
```

## Connection
- [ ] [`datdot-ui#3` datdot-ui-button](https://github.com/playproject-io/datdot-ui/issues/3)
- [ ] [`datdot-ui#10` datdot-ui-graphic](https://github.com/playproject-io/datdot-ui/issues/10)
- [ ] [`datdot-ui#77` datdot-ui-input](https://github.com/playproject-io/datdot-ui/issues/77)
- [ ] [`datdot-ui#78` datdot-ui-label](https://github.com/playproject-io/datdot-ui/issues/78)
