### ISSUE TITLE
[UI] Activity

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#104]
# Activity
![image](https://user-images.githubusercontent.com/9526525/118279149-61795800-b4fd-11eb-90d1-4d58cfa9e2f1.png)

![image](https://user-images.githubusercontent.com/9526525/118279185-6d651a00-b4fd-11eb-93b0-ceaaac08c67d.png)

![image](https://user-images.githubusercontent.com/9526525/118279277-8b327f00-b4fd-11eb-945e-7f8c0705087e.png)

![image](https://user-images.githubusercontent.com/9526525/118279343-9d142200-b4fd-11eb-8423-53e69bcf5059.png)

```js
require('datdot-ui-graphic')
require('datdot-ui-pie-chart')
require('datdot-ui-user-avatar')
require('datdot-ui-identicon')
```

## Connection
- [ ] [`datdot-ui#3` datdot-ui-button](https://github.com/playproject-io/datdot-ui/issues/3)
- [ ] [`datdot-ui#10` datdot-ui-graphic](https://github.com/playproject-io/datdot-ui/issues/10)
- [ ] [`datdot-ui#69` datdot-ui-charts](https://github.com/playproject-io/datdot-ui/issues/69)
