### ISSUE TITLE
[UI] Range slider

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#11]
# Range slider
#### Default
![image](https://user-images.githubusercontent.com/9526525/103147389-74c69980-478f-11eb-8e9f-10cffdfc14c8.png)
#### Range select
![image](https://user-images.githubusercontent.com/9526525/103147386-6a0c0480-478f-11eb-8a18-00bd8725ea72.png)
## @todo:
- [x] Add CSS style
- [ ] Import ui-domlog
- [ ] Refactor code(protocol, receive, recipients)
- [ ] On ```keyup``` changes value

#### Browsers testing (Laptop/Mobile/Tablet)
- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Opera
- [x] Edge (only laptop)

#### Device testing
* iPhone 6s Plus, iPad mini, simulator iPhone and iPad
* Maybe will use simulator with Android
---

**Comment by serapath** [comment]
# Range slider
#### Default
![image](https://user-images.githubusercontent.com/9526525/103300109-1886a280-4a39-11eb-8a64-483c6ba107a5.png)

#### Range select
![image](https://user-images.githubusercontent.com/9526525/103299991-d1001680-4a38-11eb-8464-f395972a0221.png)

**Comment by serapath** [comment]
> @ninabreznik 
> [**worklog `2022.04.07` - locking UI elements**](https://youtu.be/X8wpMNnAW2E) 

Notes:
- v.0.0.1-alpha: ui elements, updated to use new comm protocol

### Results:
**v0.0.1-alpha** (using new comm proto)
- https://github.com/datdot-ui/range-slider/tree/v0.0.1-alpha

**Comment by serapath** [comment]
> @ninabreznik 
> [**worklog `2022.04.12` - versioning and documenting components**](https://youtu.be/gCKEtJ2eG8o)

**results:**

- `v0.0.1-alpha`
  - https://github.com/datdot-ui/range-slider/tree/v0.0.1-alpha
- `v0.0.0-prealpha`
    - https://github.com/datdot-ui/range-slider/tree/v0.0.0-prealpha
- updated readme
    - https://github.com/datdot-ui/range-slider
