### ISSUE TITLE
plan - add/edit - step: data config - substep: performance

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#117]
## `@todo`
* [ ] finish design
* [ ] start implementing

**Comment by fionataeyang** [comment]
# Performance

### latest

#### v18-5
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v18-5/Plans-new%20plan-step4-data%20config-bandwidth.png?raw=true)

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

#### v18-4
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v18-4/Plans-new%20plan-step4-data%20config-bandwidth.png?raw=true)

#### v18-3
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v18-3/Plans-new%20plan-step4-data%20config-bandwidth.png?raw=true)

#### v18-2
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v18-2/Plans-new%20plan-step4-data%20config-bandwidth.png?raw=true)

#### v18-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v18-1/Plans-new%20plan-step4-data%20config-bandwidth.png?raw=true)

#### v16-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v16-1/Tablet-Laptop-plans1-create%20new%20plan-step3-data%20config-performance-notify.png?raw=true)

#### v16
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v16/Tablet-Laptop-plans1-create%20new%20plan-step3-data%20config-performance.png?raw=true)

#### v15-2
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-2/Tablet-Laptop-plans-create%20new%20plan-step3-data%20config-performance.png?raw=true)

#### v15-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-1/Tablet-Laptop-plans-create%20new%20plan-step3-data%20config-performance.png?raw=true)

#### v15
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15/Tablet-Laptop-plans-create%20new%20plan-step3-data%20config-performance.png?raw=true)

#### v14
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v14/Tablet-Laptop-plans-create%20new%20plan-step7%20performance%20%E2%80%93%201.png?raw=true)

#### v13-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v13-1/Tablet-Laptop-plans%E2%80%93plan%20created-multiple%20data-performance.png?raw=true)

#### v13
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v13/Tablet-Laptop-plans%E2%80%93plan%20created-multiple%20data-performance.png?raw=true)

**Comment by fionataeyang** [comment]
# Location

```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-card')
require('datdot-ui-list')
require('datdot-ui-location-flags-tag')
require('datdot-ui-pin-map')

// components
require('datdot-ui-plan-summary')
require('datdot-ui-mainsteps')
require('datdot-ui-substeps')

// other
require('data-cards-info')
```

## Connection
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45)
- [ ] [`datdot-ui#66` datdot-ui-plan-summary](https://github.com/playproject-io/datdot-ui/issues/66)
- [ ] [`datdot-ui#86` datdot-ui-card](https://github.com/playproject-io/datdot-ui/issues/86)
- [ ] [`datdot-ui#72` datdot-ui-list](https://github.com/playproject-io/datdot-ui/issues/72)
- [ ] [`datdot-ui#96` datdot-ui-mainsteps](https://github.com/playproject-io/datdot-ui/issues/96)
- [ ] [`datdot-ui#97` datdot-ui-substeps](https://github.com/playproject-io/datdot-ui/issues/97)
- [ ] [`datdot-ui#93` datdot-ui-pin-map](https://github.com/playproject-io/datdot-ui/issues/93)
- [ ] [`datdot-ui#101` datdot-ui-location-flag-tag](https://github.com/playproject-io/datdot-ui/issues/101)

## Pages
- [ ] [`datdot-ui#22` screen: plan](https://github.com/playproject-io/datdot-ui/issues/22)
- [ ] [`datdot-ui#18` plan - add/edit - step: input title](https://github.com/playproject-io/datdot-ui/issues/18)
- [ ] [`datdot-ui#19` plan - add/edit - step: duration](https://github.com/playproject-io/datdot-ui/issues/19)
- [ ] [`datdot-ui#20` plan - add/edit - step: swarm key](https://github.com/playproject-io/datdot-ui/issues/20)
- [ ] [`datdot-ui#21` plan - add/edit - step: data config - substep: select feeds & chunks](https://github.com/playproject-io/datdot-ui/issues/44)
- [ ] [`datdot-ui#44` plan - add/edit - step: data config - substep: schedule](https://github.com/playproject-io/datdot-ui/issues/44)
- [ ] [`datdot-ui#27` plan - add/edit - step: data config](https://github.com/playproject-io/datdot-ui/issues/27)
- [ ] [`datdot-ui#23` screen: user](https://github.com/playproject-io/datdot-ui/issues/23)
- [ ] [`datdot-ui#24` screen: work](https://github.com/playproject-io/datdot-ui/issues/24)
