### ISSUE TITLE
implement-user-screen

### ISSUE THREAD

**Issue by ninabreznik** [playproject-io/datdot-ui#139]
- [x] [`datdot-ui#56` user - dashboard](https://github.com/playproject-io/datdot-ui/issues/56)  
   - [x] [`datdot-ui#35` user - add new account - option](https://github.com/playproject-io/datdot-ui/issues/35)  
   - [x] [`datdot-ui#32` user - add new account - create new account](https://github.com/playproject-io/datdot-ui/issues/32)  
   - [x] [`datdot-ui#34` user - add new account - seed phrase](https://github.com/playproject-io/datdot-ui/issues/34)  
  - [x] [`datdot-ui#36` user - add new account - proof seed phrase](https://github.com/playproject-io/datdot-ui/issues/36)  
  - [x] [`datdot-ui#33` user - add new account - import account](https://github.com/playproject-io/datdot-ui/issues/33)  
   - [x] [`datdot-ui#37` user - add new account - import account - account information](https://github.com/playproject-io/datdot-ui/issues/37)
   - [x] [`datdot-ui#38` user -  switch account](https://github.com/playproject-io/datdot-ui/issues/38)
   - [x] [`datdot-ui#42` user -  switch account - enter password](https://github.com/playproject-io/datdot-ui/issues/42)
   - [x] [`datdot-ui#40` user -  edit account](https://github.com/playproject-io/datdot-ui/issues/40)
   - [x] [`datdot-ui#41` user -  transfer](https://github.com/playproject-io/datdot-ui/issues/41)
   - [x] [`datdot-ui#39` user -  transactions activity](https://github.com/playproject-io/datdot-ui/issues/39)

### Sub components
- [ ] [`datdot-ui#3` datdot-ui-button](https://github.com/playproject-io/datdot-ui/issues/3)
- [ ] [`datdot-ui#10` datdot-ui-graphic](https://github.com/playproject-io/datdot-ui/issues/10) 
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45)
- [ ] [`datdot-ui#46` datdot-ui-action](https://github.com/playproject-io/datdot-ui/issues/46)
- [ ] [`datdot-ui#54` datdot-ui-custom-action-bar](https://github.com/playproject-io/datdot-ui/issues/54)
- [ ] [`datdot-ui#68` datdot-ui-tooltip](https://github.com/playproject-io/datdot-ui/issues/68)
- [ ] [`datdot-ui#35` user - add new account - option](https://github.com/playproject-io/datdot-ui/issues/35)

**Comment by ninabreznik** [comment]
# Default
```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-action')
require('datdot-ui-button')
require('datdot-ui-graphic')
require('datdot-ui-tooltip')

// components
require('datdot-ui-custom-action-bar')

// call actions
require('create-new-account')
require('import-account')
```
## Pages
- [ ] [`datdot-ui#32` user - create new account](https://github.com/playproject-io/datdot-ui/issues/32)
- [ ] [`datdot-ui#33` user - import account](https://github.com/playproject-io/datdot-ui/issues/33)
- [ ] [`datdot-ui#22` SCREEN: plan](https://github.com/playproject-io/datdot-ui/issues/22)
- [ ] [`datdot-ui#24` SCREEN: work](https://github.com/playproject-io/datdot-ui/issues/24)

**Comment by ninabreznik** [comment]
> ## `@todo`
> * [ ]  [implement-user-dashboard #176](https://github.com/playproject-io/datdot-ui/issues/176)
> * [ ]  [implement-user-add-new-account #175](https://github.com/playproject-io/datdot-ui/issues/175)
> * [ ]  [implement-user-switch-account #178](https://github.com/playproject-io/datdot-ui/issues/178)
> * [ ]  [implement-user-switch-account-enter-password #177](https://github.com/playproject-io/datdot-ui/issues/177)

> * [ ]  [implement-user-transfer #180](https://github.com/playproject-io/datdot-ui/issues/180)
> * [ ]  [implement-user-transactions-activity #181](https://github.com/playproject-io/datdot-ui/issues/181)
