### ISSUE TITLE
[Design] Plan - Data

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#14]
# Data
@todo design
- [x] tabs

### Update
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v14/Tablet-Laptop-plans%E2%80%93plan%20created-first%20data%20information.png?raw=true)

---

### Issue report
Currently lack some informations about performance.
It may needs to improve UI later when see some informations need to remove or add.

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

#### v13
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v13/Tablet-Laptop-plans%E2%80%93plan%20created-first%20data%20information.png?raw=true)

#### v11
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v12/Tablet-Laptop-plans-plan-data%20info.png?raw=true)

#### v9
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v9/Tablet-Laptop-plans-plan%20created.png?raw=true)

#### v8
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v8/Tablet-Laptop-plans-plan%20created.png?raw=true)

#### v7
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v7/Tablet-Laptop-plans-created%20plan.png?raw=true)

#### v6
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v6/Tablet-Laptop-plans-created%20plan.png?raw=true)

#### v4
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v4/Tablet-Laptop-feeds-new%20sponsor%20info-block%20info.png?raw=true)

#### v3
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v3/Mobile-dashboard-data%20entries.png?raw=true)

#### v2
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v2/Tablet-Laptop-archives%20list-store%20data-filter-backer%20by%20all.png?raw=true)

**Comment by serapath** [comment]
# Data

### latest
#### Plan published
v16
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v16/Tablet-Laptop-plans1-dashboard.png?raw=true)

Current plan
![image](https://user-images.githubusercontent.com/9526525/110209906-f6dae900-7ec9-11eb-8163-612fad779c40.png)

#### Actions
Stop and remove plan
![image](https://user-images.githubusercontent.com/9526525/110209929-2853b480-7eca-11eb-8b48-884828d20006.png)

Edit plan
![image](https://user-images.githubusercontent.com/9526525/110209932-2c7fd200-7eca-11eb-8418-678fb43a4ec7.png)

Pause plan (Hold to pay subscribe)
![image](https://user-images.githubusercontent.com/9526525/110209934-30135900-7eca-11eb-8cf9-bf240a673fde.png)

Run plan (Continue to pay subscribe)
![image](https://user-images.githubusercontent.com/9526525/110209937-33a6e000-7eca-11eb-8734-467ca19fa9f7.png)

 
---

### Issue report
Currently lack some informations about performance.
It may needs to improve UI later when see some informations need to remove or add.

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

#### v15-3
Plans1 layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-3/Tablet-Laptop-plans1-plan1%20created.png?raw=true)

Plans layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-3/Tablet-Laptop-plans-plan1%20created.png?raw=true)

#### v15-2
Plans1 layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-2/Tablet-Laptop-plans1-plan1%20created.png?raw=true)

Plans layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-2/Tablet-Laptop-plans-plan1%20created.png?raw=true)

#### v15-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-1/Tablet-Laptop-plans-plan1%20created.png?raw=true)

#### v15
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15/Tablet-Laptop-plans%E2%80%93plan%20created-data%20information.png?raw=true)

#### v14
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v14/Tablet-Laptop-plans%E2%80%93plan%20created-first%20data%20information.png?raw=true)

#### v13
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v13/Tablet-Laptop-plans%E2%80%93plan%20created-first%20data%20information.png?raw=true)

#### v11
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v12/Tablet-Laptop-plans-plan-data%20info.png?raw=true)

#### v9
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v9/Tablet-Laptop-plans-plan%20created.png?raw=true)

#### v8
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v8/Tablet-Laptop-plans-plan%20created.png?raw=true)

#### v7
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v7/Tablet-Laptop-plans-created%20plan.png?raw=true)

#### v6
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v6/Tablet-Laptop-plans-created%20plan.png?raw=true)

#### v4
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v4/Tablet-Laptop-feeds-new%20sponsor%20info-block%20info.png?raw=true)

#### v3
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v3/Mobile-dashboard-data%20entries.png?raw=true)

#### v2
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v2/Tablet-Laptop-archives%20list-store%20data-filter-backer%20by%20all.png?raw=true)

**Comment by fionataeyang** [comment]
# Publish
```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-card')
require('datdot-ui-list')
require('datdot-ui-line-chart')
require('datdot-ui-pin-map')
requrire('datdot-ui-chart-legend')
require('datdot-ui-chart-range')
require('datdot-ui-chart-scalebar')
require('datdot-ui-account-selector')
require('datdot-ui-modal')

// components
require('datdot-ui-plan-summary')
require('datdot-ui-mainsteps')

// call actions
require('stop-plan')
require('pause-plan')
require('play-plan')
```

## Connection
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45)
- [ ] [`datdot-ui#66` datdot-ui-plan-summary](https://github.com/playproject-io/datdot-ui/issues/66)
- [ ] [`datdot-ui#86` datdot-ui-card](https://github.com/playproject-io/datdot-ui/issues/86)
- [ ] [`datdot-ui#72` datdot-ui-list](https://github.com/playproject-io/datdot-ui/issues/72)
- [ ] [`datdot-ui#93` datdot-ui-pin-map](https://github.com/playproject-io/datdot-ui/issues/93)
- [ ] [`datdot-ui#69` datdot-ui-linechart](https://github.com/playproject-io/datdot-ui/issues/69)
- [ ] [`datdot-ui#114` datdot-ui-chart-scalebar](https://github.com/playproject-io/datdot-ui/issues/114)
- [ ] [`datdot-ui#100` datdot-ui-chart-range](https://github.com/playproject-io/datdot-ui/issues/100)
- [ ] [`datdot-ui#113` datdot-ui-chart-legend](https://github.com/playproject-io/datdot-ui/issues/113)
- [ ] [`datdot-ui#104` datdot-ui-activity](https://github.com/playproject-io/datdot-ui/issues/104)
- [ ] [`datdot-ui#84` datdot-ui-title](https://github.com/playproject-io/datdot-ui/issues/84)
- [ ] [`datdot-ui#99` datdot-ui-search](https://github.com/playproject-io/datdot-ui/issues/99)
- [ ] [`datdot-ui#55` datdot-ui-sort](https://github.com/playproject-io/datdot-ui/issues/55)
- [ ] [`datdot-ui#53` datdot-ui-filter](https://github.com/playproject-io/datdot-ui/issues/53)
- [ ] [`datdot-ui#67` datdot-ui-modal](https://github.com/playproject-io/datdot-ui/issues/67)

## Pages
* [ ] [`datdot-ui#23` screen: user](https://github.com/playproject-io/datdot-ui/issues/23)
* [ ] [`datdot-ui#24` screen: work](https://github.com/playproject-io/datdot-ui/issues/24)

## Call actions
- [ ] [`datdot-ui#35` user - add new account - option](https://github.com/playproject-io/datdot-ui/issues/35)
- [ ] [`datdot-ui#54` datdot-ui-custom-action-bar](https://github.com/playproject-io/datdot-ui/issues/54)
- [ ] [`datdot-ui#29` notifications/help overlay box](https://github.com/playproject-io/datdot-ui/issues/29)
