### ISSUE TITLE
wireframe-plan-screen

### ISSUE THREAD

**Issue by ninabreznik** [playproject-io/datdot-ui#140]
* [x] page title
  * [x] total plans area (no plan yet)
  * [x] actions + search bar
  * [x] [`datdot-ui#14` plan - dashboard](https://github.com/playproject-io/datdot-ui/issues/14)  
  * [x] [`datdot-ui#18` plan - add/edit - step: input title](https://github.com/playproject-io/datdot-ui/issues/18)
  * [x] [`datdot-ui#19` plan - add/edit - step: duration](https://github.com/playproject-io/datdot-ui/issues/19)
  * [x] [`datdot-ui#20` plan - add/edit - step: swarm key](https://github.com/playproject-io/datdot-ui/issues/20)
  * [x] [`datdot-ui#27` plan - add/edit - step: data config](https://github.com/playproject-io/datdot-ui/issues/27)
     - [x] [`datdot-ui#21` plan - add/edit - step: data config - substep: select feeds & chunks](https://github.com/playproject-io/datdot-ui/issues/21)
     - [x] [`datdot-ui#44` plan - add/edit - step: data config - substep: schedule](https://github.com/playproject-io/datdot-ui/issues/44)
     - [x] [`datdot-ui#28` plan - add/edit - step: data config - substep: location](https://github.com/playproject-io/datdot-ui/issues/28)
     - [x] [`datdot-ui#117` plan - add/edit - step: data config - substep: performance](https://github.com/playproject-io/datdot-ui/issues/117)
  * [x] [`datdot-ui#16` plan - add/edit - step: publish](https://github.com/playproject-io/datdot-ui/issues/16)
  * [x] [`datdot-ui#15` plan - activity](https://github.com/playproject-io/datdot-ui/issues/15)

**Comment by ninabreznik** [comment]
# Plan
### latest
#### v18-2
![image](https://raw.githubusercontent.com/datdotorg/datdot-assets/main/design/datdot-app-v18-2/Plans-default.png)

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

#### v18-2
![image](https://raw.githubusercontent.com/datdotorg/datdot-assets/main/design/datdot-app-v18-2/Plans-default.png)

#### v18-1
![image](https://raw.githubusercontent.com/datdotorg/datdot-assets/main/design/datdot-app-v18-1/Plans-default.png)

#### v16
![image](https://raw.githubusercontent.com/datdotorg/datdot-assets/main/design/datdot-app-v16/Tablet-Laptop-plans1.png)

#### v15-3
Plans1 layout
![image](https://raw.githubusercontent.com/datdotorg/datdot-assets/main/design/datdot-app-v15-3/Tablet-Laptop-plans1.png)

#### v15-2
Plans1 layout
![image](https://raw.githubusercontent.com/datdotorg/datdot-assets/main/design/datdot-app-v15-2/Tablet-Laptop-plans1.png)

Plans layout
![image](https://raw.githubusercontent.com/datdotorg/datdot-assets/main/design/datdot-app-v15-2/Tablet-Laptop-plans.png?raw=true)

#### v15-1
![image](https://raw.githubusercontent.com/datdotorg/datdot-assets/main/design/datdot-app-v15-1/Tablet-Laptop-plans.png?raw=true)

#### v13-1
![image](https://raw.githubusercontent.com/datdotorg/datdot-assets/main/design/datdot-app-v13-1/Tablet-Laptop-plans.png?raw=true)

#### v12
![image](https://raw.githubusercontent.com/datdotorg/datdot-assets/main/design/datdot-app-v12/Tablet-Laptop-plans.png?raw=true)

#### v8
![image](https://raw.githubusercontent.com/datdotorg/datdot-assets/main/design/datdot-app-v8/Tablet-Laptop-plans-default.png?raw=true)

#### v7
![image](https://raw.githubusercontent.com/datdotorg/datdot-assets/master/design/datdot-app-v7/Tablet-Laptop-plans-default.png)

#### v6
![image](https://raw.githubusercontent.com/datdotorg/datdot-assets/main/design/datdot-app-v6/Tablet-Laptop-plans-default.png)

#### v5
![image](https://raw.githubusercontent.com/datdotorg/datdot-assets/main/design/datdot-app-v5/Tablet-Laptop-data-no%20data.png)

#### v4
![image](https://raw.githubusercontent.com/datdotorg/datdot-assets/main/design/datdot-app-v4/Tablet-Laptop-feeds-no%20data.png)

#### v0
![image](https://raw.githubusercontent.com/datdotorg/datdot-assets/main/design/datdot-app-v0/Datdot%20app-dashboard-empty.png)
