### ISSUE TITLE
implement-plan-screen

### ISSUE THREAD

**Issue by ninabreznik** [playproject-io/datdot-ui#141]
* [ ] **plan summary card**
      <details>

        * [x] the "plan summary card" on top does not need "edit" icons, because user can just click the progress step
        * [x] the "plan summary" card on top is but just maybe it could look less like editable input fields, but just display the summary
        * [x] the "plan summary card" could maybe use the entire width of the screen
        * [x] maybe the main number on the "plan summary card" could have a "price icon" so user knows what it means
        * [x] also the plan name could have a swarmkey "identicon" to represent the swarmkey next to the plan name as a unique generated little icon
            * https://en.wikipedia.org/wiki/Identicon
            * [more examples](https://www.google.com/search?q=identicon&newwindow=1&source=lnms&tbm=isch&biw=952&bih=930)
        * [x] also maybe feeds & chunks could be merged and we could add total size all into a single line, like:
          * `"187 feeds (12.2k chunks, 50.3 GB)"`
        * [x] and we could add a little thumbnail world map to show approximate locations
        * [x] maybe first is "name", with an identicon to represent the "swarm key"
            * [ ] remove "swarmkey" field once it is represented in the summary as identicon
        * [ ] maybe we can combine the "chart" (below map) which always goes from duration "start" to "end", with the duration date fields into one so we have more space for chart and map
        * [ ] ...maybe there is even space to add the section (total price/avg. chunk price) which is usually on the last step before publish?  ...like data cards show total price, so why not make "plan summary" also show total price
        * [x] then the duration should become a little price chart (from "start" to "end" of duration)
          * [ ] chart can look small and single line like for price on https://coinmarketcap.com/
        * [ ] when user clicks somewhere on some **time point line** in the chart, the little **map** will show for that point in time
            * [ ] the **time point line** could otherwise automatically run from "start" to "end duration in an infinite loop
            * [ ] changes in gradient color red to yellow to green could indicate the PERFORMANCE in each region on the map
            * [ ] changes in saturation or opacity could show "how much" data is hosted in that specific regions on the map in each time
                * maybe like: https://giphy.com/gifs/pri-new-politics-V4oirjglQ4Ula
                * or https://giphy.com/gifs/new-harvest-newharvest-TigoNK9VCwYyNrjlys
                * or https://giphy.com/gifs/mlb-5xaOcLuiDLsI6EuAcHC
                * or https://giphy.com/gifs/mlb-yoJC2I36Khrm8MvS8M
        </details>

    * [ ] **data card**
      <details>

         * [x] add size in bytes (MB/GB/TB...) to data summary card [here](https://imgur.com/Iob7GBG.png)
         * [ ] **feedback nav/action bar**
         * [ ] on data config, i love the back/forward buttons, but:
         * [ ] when a user already has some "data cards" and wants to add a new "data card" and filled out some steps
             * [x] maybe user wants to cancel only that card, but there is no "sub cancel" button
             * [x] also, on the last step of the "sub progress bar", the "next" button could be the "confirm" button
             * [x] maybe we don't need a "back button", because the user can just click the "progress step" directly
             * [ ] maybe we could replace the "back button" with the "sub cancel" button?
         *  [ ] for the primary progress bar, we could:
             * [x] merge the primary progress bar (newplan/duration/swarm/dataconfig/publish) with the action bar below
             * [x] so the "cancel button" could move right before the (newplan) step
             * [x] we don't need a "previous step" becaue a user could click directly on a "progress step"
             * [x] the "confirm/next" button could show after the (publish) step
         *  [x] maybe on each progress step, it should be visually clear to the user they can click it
         *  [ ] maybe we could use "warning" color and "focus" color even on wireframes to faster see where the user is
       </details>

    * [ ] **plans main screen**
       <details>

        * [x] the [tabs (performance, location)](https://fionataeyang.github.io/datdot-ui/design/datdot-app-v18-1/prototypes/Plans_plan_list_info_location.html) should probably be below, because now they are more "navigation bar")
          * [x] also it doesn't need to show "Plan1" in the map on the bottom left, because its already selected above
        * [x] maybe in the main plan screen action bar, the `"play"` button can change into `"pause"` when user clicks
        * [ ] also maybe the action bar already has two parts and it should improve grouping:
          * [ ] actions that change something like transactions (e.g. pause/play/delete/add_plan) icons
          * [ ] actions which just change the view (e.g. sort/filter/search/...) icons
       </details>

    * [ ] **activites screen**
       <details>
        * also on the [activities screen](https://datdotorg.github.io/datdot-assets/design/datdot-app-v18-1/prototypes/Plans_activity.html)
        * [ ] there are lots of icons, but sometimes i forget what they do, so maybe we need:
          * [x] a HELP icon?
          * [x] when you click HELP, you can then go into help mode and click any part of the screen
            * like other icons, etc..
            * [x] and when you click in HELP mode, it shows you a "info notification" to explain what it is
       </details>
    * [ ] **alternative**
       <details>

      * [ ] maybe the action bar has a "..." (more) icon and when you click it, it shows a menu with other icons
        * [x] in that menu, icons have a text to show what the actions means
        * [x] and you can select/unselect them to add to the "action bar" as quick action icon
        * [x] so basically you can customize your action bar a bit
   </details>

### Sub components

- [ ] [`datdot-ui#3` datdot-ui-button](https://github.com/playproject-io/datdot-ui/issues/3)
- [ ] [`datdot-ui#10` datdot-ui-icon](https://github.com/playproject-io/datdot-ui/issues/10) 
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45)
- [ ] [`datdot-ui#46` datdot-ui-action](https://github.com/playproject-io/datdot-ui/issues/46)
- [ ] [`datdot-ui#54` datdot-ui-custom-action-bar](https://github.com/playproject-io/datdot-ui/issues/54)
- [ ] [`datdot-ui#68` datdot-ui-tooltip](https://github.com/playproject-io/datdot-ui/issues/68)
