### ISSUE TITLE
[Design] Plan - Activity

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#15]
#  Activity
@todo design
- [x] tabs
- [ ] filter
- [x] canlendar
- [x] transaction list
- [ ] transaction options(cancel action)

### Update
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v14/Tablet-Laptop-plans%E2%80%93plan%20created-first%20data-activity.png?raw=true)
---

### Issue report
Currently lack some informations about performance.
It may needs to improve UI later when see some informations need to remove or add.
---

### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

#### v12
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v12/Tablet-Laptop-plans-plan-activity.png?raw=true)

#### v10
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v10/Tablet-Laptop-plans-plan-activity.png?raw=true)

#### v9
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v9/Tablet-Laptop-plans-plan%20created.png?raw=true)

#### v7
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v7/Tablet-Laptop-plans-list.png?raw=true)

#### v6
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v6/Tablet-Laptop-plans-list.png?raw=true)

#### v5
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v5/Tablet-Laptop-data-grid%20view.png?raw=true)

#### v4
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v4/Tablet-Laptop-feeds.png?raw=true)

**Comment by serapath** [comment]
#  Activity

### latest
v16
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v16/Tablet-Laptop-plans1-activity.png?raw=true)

Filter option for Pending, Success and Cancel
![image](https://user-images.githubusercontent.com/9526525/110209822-8a5fea00-7ec9-11eb-933a-40176d490f4a.png)

---

### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

#### v15-3
Plans1 layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-3/Tablet-Laptop-plans1%E2%80%93plan%20created-first%20data-activity.png?raw=truee)

Plans layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-3/Tablet-Laptop-plans%E2%80%93plan%20created-first%20data-activity.png?raw=true)

#### v15-2
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-2/Tablet-Laptop-plans%E2%80%93plan%20created-first%20data-activity.png?raw=true)

#### v15-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-1/Tablet-Laptop-plans%E2%80%93plan%20created-first%20data-activity.png?raw=true)

#### v14
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v14/Tablet-Laptop-plans%E2%80%93plan%20created-first%20data-activity.png?raw=true)

#### v12
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v12/Tablet-Laptop-plans-plan-activity.png?raw=true)

#### v10
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v10/Tablet-Laptop-plans-plan-activity.png?raw=true)

#### v9
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v9/Tablet-Laptop-plans-plan%20created.png?raw=true)

#### v7
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v7/Tablet-Laptop-plans-list.png?raw=true)

#### v6
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v6/Tablet-Laptop-plans-list.png?raw=true)

#### v5
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v5/Tablet-Laptop-data-grid%20view.png?raw=true)

#### v4
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v4/Tablet-Laptop-feeds.png?raw=true)

**Comment by fionataeyang** [comment]
# Activity
```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-action')
require('datdot-ui-button')
require('datdot-ui-graphic')
require('datdot-ui-tooltip')
require('datdot-ui-list')
require('datdot-ui-activity')
require('datdot-ui-card')
require('datdot-ui-search')
require('datdot-ui-sort')
require('datdot-ui-filter')
require('datdot-ui-pin-map')
require('datdot-ui-title')

// components
require('datdot-ui-custom-action-bar')
require('datdot-ui-modal')

// call actions
require('cancel-payment')
```

## Connection
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45)
- [ ] [`datdot-ui#46` datdot-ui-action](https://github.com/playproject-io/datdot-ui/issues/46)
- [ ] [`datdot-ui#3` datdot-ui-button](https://github.com/playproject-io/datdot-ui/issues/3)
- [ ] [`datdot-ui#10` datdot-ui-graphic](https://github.com/playproject-io/datdot-ui/issues/10) 
- [ ] [`datdot-ui#68` datdot-ui-tooltip](https://github.com/playproject-io/datdot-ui/issues/68)
- [ ] [`datdot-ui#72` datdot-ui-list](https://github.com/playproject-io/datdot-ui/issues/72)
- [ ] [`datdot-ui#104` datdot-ui-activity](https://github.com/playproject-io/datdot-ui/issues/104)
- [ ] [`datdot-ui#86` datdot-ui-card](https://github.com/playproject-io/datdot-ui/issues/86)
- [ ] [`datdot-ui#99` datdot-ui-search](https://github.com/playproject-io/datdot-ui/issues/99)
- [ ] [`datdot-ui#55` datdot-ui-sort](https://github.com/playproject-io/datdot-ui/issues/55)
- [ ] [`datdot-ui#53` datdot-ui-filter](https://github.com/playproject-io/datdot-ui/issues/53)
- [ ] [`datdot-ui#93` datdot-ui-pin-map](https://github.com/playproject-io/datdot-ui/issues/93)
- [ ] [`datdot-ui#84` datdot-ui-pin-map](https://github.com/playproject-io/datdot-ui/issues/84)

## Pages
- [ ] [`datdot-ui#32` user - create new account](https://github.com/playproject-io/datdot-ui/issues/32)
- [ ] [`datdot-ui#18` plan - add/edit - step: input title](https://github.com/playproject-io/datdot-ui/issues/18)
- [ ] [`datdot-ui#14` plan - dashboard](https://github.com/playproject-io/datdot-ui/issues/14)
- [ ] [`datdot-ui#23` screen: user](https://github.com/playproject-io/datdot-ui/issues/23)
- [ ] [`datdot-ui#24` screen: work](https://github.com/playproject-io/datdot-ui/issues/24)

## Call actions
- [ ] [`datdot-ui#35` user - add new account - option](https://github.com/playproject-io/datdot-ui/issues/35)
- [ ] [`datdot-ui#38` user - switch account](https://github.com/playproject-io/datdot-ui/issues/38)
- [ ] [`datdot-ui#42` user - switch account - enter password](https://github.com/playproject-io/datdot-ui/issues/42)
- [ ] [`datdot-ui#40` user - edit account](https://github.com/playproject-io/datdot-ui/issues/40)
- [ ] [`datdot-ui#116` user - remove account](https://github.com/playproject-io/datdot-ui/issues/116)
- [ ] [`datdot-ui#41` user - transfer](https://github.com/playproject-io/datdot-ui/issues/41)
- [ ] [`datdot-ui#55` datdot-ui-sort](https://github.com/playproject-io/datdot-ui/issues/55)
- [ ] [`datdot-ui#53` datdot-ui-filter](https://github.com/playproject-io/datdot-ui/issues/53)
- [ ] [`datdot-ui#54` datdot-ui-custom-action-bar](https://github.com/playproject-io/datdot-ui/issues/54)
- [ ] [`datdot-ui#29` notifications/help overlay box](https://github.com/playproject-io/datdot-ui/issues/29)
