### ISSUE TITLE
implement-work-screen

### ISSUE THREAD

**Issue by ninabreznik** [playproject-io/datdot-ui#155]
- [ ] [`datdot-ui#57` work - dashboard](https://github.com/playproject-io/datdot-ui/issues/57)
   - [ ] [`datdot-ui#58` work - activity](https://github.com/playproject-io/datdot-ui/issues/58)
   - [ ] [`datdot-ui#59` work - settings - steps: resources](https://github.com/playproject-io/datdot-ui/issues/59)
   - [ ] [`datdot-ui#60` work - settings - steps: reward](https://github.com/playproject-io/datdot-ui/issues/60)
   - [ ] [`datdot-ui#61` work - settings - steps: location](https://github.com/playproject-io/datdot-ui/issues/61)
   - [ ] [`datdot-ui#62` work - settings - steps: schedule](https://github.com/playproject-io/datdot-ui/issues/62)
