### ISSUE TITLE
wireframe-work-screen

### ISSUE THREAD

**Issue by ninabreznik** [playproject-io/datdot-ui#156]
- [x] [`datdot-ui#57` wireframe-work-dashboard](https://github.com/playproject-io/datdot-ui/issues/57)
   - [x] [`datdot-ui#58` wireframe-work-activity](https://github.com/playproject-io/datdot-ui/issues/58)
   - [x] [`datdot-ui#59` wireframe-work-settings - steps: resources](https://github.com/playproject-io/datdot-ui/issues/59)
   - [x] [`datdot-ui#60` wireframe-work-settings - steps: reward](https://github.com/playproject-io/datdot-ui/issues/60)
   - [x] [`datdot-ui#61` wireframe-work-settings - steps: location](https://github.com/playproject-io/datdot-ui/issues/61)
   - [x] [`datdot-ui#62` wireframe-work-settings - steps: schedule](https://github.com/playproject-io/datdot-ui/issues/62)

**Comment by ninabreznik** [comment]
### latest
#### v4
![image](https://raw.githubusercontent.com/datdotorg/datdot-assets/main/design/datdot-app-JOBS-v4/JOBS-default.png)

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

#### v3
![image](https://raw.githubusercontent.com/datdotorg/datdot-assets/main/design/datdot-app-JOBS-v3/JOBS-default.png)

#### v2
![image](https://raw.githubusercontent.com/datdotorg/datdot-assets/main/design/datdot-app-JOBS-v2/JOBS-default.png)

#### v1
![image](https://raw.githubusercontent.com/datdotorg/datdot-assets/main/design/datdot-app-JOBS-v1/JOBS-default.png)

#### v0
![image](https://raw.githubusercontent.com/datdotorg/datdot-assets/main/design/datdot-app-JOBS-v0/Tablet-Laptop-jobs-calendar.png)
