### ISSUE TITLE
[Design] Plans - Create new plan - Publish

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#16]
#  Plans - Create new plan - Publish
@todo design
- [x] Hosting information
    - Plan name
    - Duration
    - Swarm key
    - feeds and chunks card list
    - Add more feeds and chunks card list

- [x] Estimated information

### Update
Plans1 layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-3/Tablet-Laptop-plans1-create-new-plan-step4-publish.png?raw=true)

Plans layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-3/Tablet-Laptop-plans-create-new-plan-step4-publish.png?raw=true)
---

### Issue report

Currently lack some informations about performance.
It may needs to improve UI later when see some informations need to remove or add.

---

#### v15-2
Plans1 layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-2/Tablet-Laptop-plans1-create-new-plan-step4-publish.png?raw=true)

#### v15-1
Plans layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-1/Tablet-Laptop-plans-create-new-plan-step4-publish.png?raw=true)

#### v15
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15/Tablet-Laptop-plans-create-new-plan-step4-publish.png?raw=true)

#### v14
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v13/Tablet-Laptop-plans%E2%80%93create%20plan-complete.png?raw=true)

#### v12-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v12-1/Tablet-Laptop-plans%E2%80%93create%20plan-feeds%20list%20%E2%80%93%203.png?raw=true)

#### v10
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v10/Tablet-Laptop-plans-create%20new%20plan-add%20more%20schedules.png?raw=true)

#### v8
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v8/Tablet-Laptop-plans-create%20new%20plan%20by%20cabal.png?raw=true)

#### v6-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v6-1/Tablet-Laptop-plans-create%20new%20plan.png?raw=true)

#### v6
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v6/Tablet-Laptop-publish%20new%20data-add%20new%20range.png?raw=true)

#### v5
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v5/Tablet-Laptop-publish%20new%20data-add%20new%20range.png?raw=true)

#### v1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v1/Datdot%20app-hosting%20and%20service-hosting.png?raw=true)

**Comment by serapath** [comment]
#  Plans - Create new plan - Publish

### latest
v16 
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v16/Tablet-Laptop-plans1-create-new-plan-step4-publish.png?raw=true)

---
### Previous design

#### v15-3
Plans1 layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-3/Tablet-Laptop-plans1-create-new-plan-step4-publish.png?raw=true)

Plans layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-3/Tablet-Laptop-plans-create-new-plan-step4-publish.png?raw=true)

#### v15-2
Plans1 layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-2/Tablet-Laptop-plans1-create-new-plan-step4-publish.png?raw=true)

#### v15-1
Plans layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-1/Tablet-Laptop-plans-create-new-plan-step4-publish.png?raw=true)

#### v15
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15/Tablet-Laptop-plans-create-new-plan-step4-publish.png?raw=true)

#### v14
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v13/Tablet-Laptop-plans%E2%80%93create%20plan-complete.png?raw=true)

#### v12-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v12-1/Tablet-Laptop-plans%E2%80%93create%20plan-feeds%20list%20%E2%80%93%203.png?raw=true)

#### v10
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v10/Tablet-Laptop-plans-create%20new%20plan-add%20more%20schedules.png?raw=true)

#### v8
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v8/Tablet-Laptop-plans-create%20new%20plan%20by%20cabal.png?raw=true)

#### v6-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v6-1/Tablet-Laptop-plans-create%20new%20plan.png?raw=true)

#### v6
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v6/Tablet-Laptop-publish%20new%20data-add%20new%20range.png?raw=true)

#### v5
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v5/Tablet-Laptop-publish%20new%20data-add%20new%20range.png?raw=true)

#### v1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v1/Datdot%20app-hosting%20and%20service-hosting.png?raw=true)

**Comment by fionataeyang** [comment]
# Publish
```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-card')
require('datdot-ui-list')
require('datdot-ui-line-chart')
require('datdot-ui-pin-map')
requrire('datdot-ui-chart-legend')
require('datdot-ui-chart-range')
require('datdot-ui-chart-scalebar')
require('datdot-ui-account-selector')

// components
require('datdot-ui-plan-summary')
require('datdot-ui-mainsteps')

// other
require('data-cards-info')
require('estimated')
```

## Connection
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45)
- [ ] [`datdot-ui#66` datdot-ui-plan-summary](https://github.com/playproject-io/datdot-ui/issues/66)
- [ ] [`datdot-ui#86` datdot-ui-card](https://github.com/playproject-io/datdot-ui/issues/86)
- [ ] [`datdot-ui#72` datdot-ui-list](https://github.com/playproject-io/datdot-ui/issues/72)
- [ ] [`datdot-ui#96` datdot-ui-mainsteps](https://github.com/playproject-io/datdot-ui/issues/96)
- [ ] [`datdot-ui#105` datdot-ui-account-selector](https://github.com/playproject-io/datdot-ui/issues/105)
- [ ] [`datdot-ui#93` datdot-ui-pin-map](https://github.com/playproject-io/datdot-ui/issues/93)
- [ ] [`datdot-ui#69` datdot-ui-linechart](https://github.com/playproject-io/datdot-ui/issues/69)
- [ ] [`datdot-ui#114` datdot-ui-chart-scalebar](https://github.com/playproject-io/datdot-ui/issues/114)
- [ ] [`datdot-ui#100` datdot-ui-chart-range](https://github.com/playproject-io/datdot-ui/issues/100)
- [ ] [`datdot-ui#113` datdot-ui-chart-legend](https://github.com/playproject-io/datdot-ui/issues/113)

## Pages
- [ ] [`datdot-ui#22` screen: plan](https://github.com/playproject-io/datdot-ui/issues/22)
- [ ] [`datdot-ui#14` plan - dashboard](https://github.com/playproject-io/datdot-ui/issues/14)
- [ ] [`datdot-ui#23` screen: user](https://github.com/playproject-io/datdot-ui/issues/23)
- [ ] [`datdot-ui#24` screen: work](https://github.com/playproject-io/datdot-ui/issues/24)
