### ISSUE TITLE
implement-datdot-webapp

### ISSUE THREAD

**Issue by ninabreznik** [playproject-io/datdot-ui#168]
## `@todo`
* [] wireframe whole app
* [x] [`datdot-ui#139` implement-user-screen](https://github.com/playproject-io/datdot-ui/issues/139)
* [ ]  [`datdot-ui#141` implement-plan-screen](https://github.com/playproject-io/datdot-ui/issues/141)
* [ ]  [`datdot-ui#155` implement-work-screen](https://github.com/playproject-io/datdot-ui/issues/155)
* [ ]  [`datdot-ui#167` implement-apps-screen](https://github.com/playproject-io/datdot-ui/issues/167)
* [ ]   [`datdot-ui#1` implement-navigation](https://github.com/playproject-io/datdot-ui/issues/1)
* [ ]  wireframe-main-notifcation-viewer-overlay
