### ISSUE TITLE
datdot-webapp

### ISSUE THREAD

**Issue by ninabreznik** [playproject-io/datdot-ui#169]
## `@todo`
* [ ] make datdot-webapp page
  * `@input` :factory: datdot wireframes from #125
  * `@input` :question: : [`datdot-app-components`](https://github.com/datdot-ui) from #9
  * [ ] assemble the app using datdot components
  * [ ] connect ui with service.js
  * `@output` :question: : [`datdot-webapp`](https://github.com/datdotorg/datdot-webapp)

---

## `@info`
...
