### ISSUE TITLE
[Design] Plan - Default empty

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#18]
# Plan
@todo design
- [x] page title
- [x] total plans area (no plan yet)
- [x] actions + search bar

### Update
v16
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v16/Tablet-Laptop-plans1.png?raw=true)
---

### Issue report
Currently lack some informations about performance.
It may needs to improve UI later when see some informations need to remove or add.

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

#### v15-3
Plans1 layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-3/Tablet-Laptop-plans1.png?raw=true)

#### v15-2
Plans1 layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-2/Tablet-Laptop-plans1.png?raw=true)

Plans layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-2/Tablet-Laptop-plans.png?raw=true)

#### v15-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-1/Tablet-Laptop-plans.png?raw=true)

#### v13-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v13-1/Tablet-Laptop-plans.png?raw=true)

#### v12
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v12/Tablet-Laptop-plans.png?raw=true)

#### v8
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v8/Tablet-Laptop-plans-default.png?raw=true)

#### v7
![image](https://raw.githubusercontent.com/fionataeyang/datdot-ui/master/design/datdot-app-v7/Tablet-Laptop-plans-default.png)

#### v6
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v6/Tablet-Laptop-plans-default.png?raw=true)

#### v5
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v5/Tablet-Laptop-data-no%20data.png?raw=true)

#### v4
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v4/Tablet-Laptop-feeds-no%20data.png?raw=true)

#### v0
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v0/Datdot%20app-dashboard-empty.png?raw=true)

**Comment by fionataeyang** [comment]
#  Activity
### latest
#### v18-4
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v18-4/Plans-new%20plan-step1-name.png?raw=true)

---

### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

#### v18-3
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v18-3/Plans-new%20plan-step1-name.png?raw=true)

#### v18-2
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v18-2/Plans-new%20plan-step1-name.png?raw=true)

#### v18
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v18/Plans-new%20plan-step1-name.png?raw=true)

#### v17
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v17/Tablet-Laptop-plans1-new%20plan.png?raw=true)

#### v16
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v16/Tablet-Laptop-plans1-create%20new%20plan-step1%20duration-end.png?raw=true)

#### v15-3
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-3/Tablet-Laptop-plans1-create%20new%20plan.png?raw=true)

#### v15-2
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-2/Tablet-Laptop-plans-create%20new%20plan.png?raw=true)

#### v15-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-1/Tablet-Laptop-plans-create%20new%20plan.png?raw=true)

#### v15
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15/Tablet-Laptop-plans-create%20new%20plan.png?raw=true)

**Comment by fionataeyang** [comment]
# Input title
```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-plan-name')

// components
require('datdot-ui-plan-summary')
require('datdot-ui-mainsteps')
```

## Connection
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45)
- [ ] [`datdot-ui#103` datdot-ui-plan-name](https://github.com/playproject-io/datdot-ui/issues/103)
- [ ] [`datdot-ui#66` datdot-ui-plan-summary](https://github.com/playproject-io/datdot-ui/issues/66)
- [ ] [`datdot-ui#96` datdot-ui-mainsteps](https://github.com/playproject-io/datdot-ui/issues/96)
