### ISSUE TITLE
[Design] Plan - create new plan - duration

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#19]
# Duration
@todo design

### Update 
v16
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v16/Tablet-Laptop-plans1-create%20new%20plan-step1%20duration-end.png?raw=true)

---

### Issue report
Currently lack some informations about performance.
It may needs to improve UI later when see some informations need to remove or add.

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

#### v15-2
Plans1 layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-2/Tablet-Laptop-plans1-create%20new%20plan-step1%20duration-end.png?raw=true)

Plans layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-2/Tablet-Laptop-plans-create%20new%20plan-step1%20duration-end.png?raw=true)

#### v15-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-1/Tablet-Laptop-plans-create%20new%20plan-step1%20schedule-end.png?raw=true)

#### v13-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v13-1/Tablet-Laptop-plans-create%20new%20plan-step1%20schedule-end.png?raw=true)

#### v13
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v13/Tablet-Laptop-plans-create%20new%20plan-step1%20schedule-end.png?raw=true)

#### v12-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v12-1/Tablet-Laptop-plans-create%20new%20plan-step1%20schedule.png?raw=true)

#### v12
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v12/Tablet-Laptop-plans-create%20new%20plan-data%20subscribe-step1%20schedule.png?raw=true)

#### v11
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v11/Tablet-Laptop-plans-create%20new%20plan-data%20subscribe-step1%20schedule.png?raw=true)

#### v10
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v10/Tablet-Laptop-plans-create%20new%20plan-data%20subscribe-step1%20schedule.png?raw=true)

#### v6
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v6/Tablet-Laptop-plans-create%20new%20plan-schedule.png?raw=true)

**Comment by serapath** [comment]
# Duration

### latest
v16
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v16/Tablet-Laptop-plans1-create%20new%20plan-step1%20duration-end.png?raw=true)

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

#### v15-2
Plans1 layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-2/Tablet-Laptop-plans1-create%20new%20plan-step1%20duration-end.png?raw=true)

Plans layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-2/Tablet-Laptop-plans-create%20new%20plan-step1%20duration-end.png?raw=true)

#### v15-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-1/Tablet-Laptop-plans-create%20new%20plan-step1%20schedule-end.png?raw=true)

#### v13-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v13-1/Tablet-Laptop-plans-create%20new%20plan-step1%20schedule-end.png?raw=true)

#### v13
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v13/Tablet-Laptop-plans-create%20new%20plan-step1%20schedule-end.png?raw=true)

#### v12-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v12-1/Tablet-Laptop-plans-create%20new%20plan-step1%20schedule.png?raw=true)

#### v12
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v12/Tablet-Laptop-plans-create%20new%20plan-data%20subscribe-step1%20schedule.png?raw=true)

#### v11
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v11/Tablet-Laptop-plans-create%20new%20plan-data%20subscribe-step1%20schedule.png?raw=true)

#### v10
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v10/Tablet-Laptop-plans-create%20new%20plan-data%20subscribe-step1%20schedule.png?raw=true)

#### v6
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v6/Tablet-Laptop-plans-create%20new%20plan-schedule.png?raw=true)

**Comment by fionataeyang** [comment]
# Input title
```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-plan-name')

// components
require('datdot-ui-plan-summary')
require('datdot-ui-mainsteps')
```

## Connection
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45)
- [ ] [`datdot-ui#103` datdot-ui-plan-name](https://github.com/playproject-io/datdot-ui/issues/103)
- [ ] [`datdot-ui#66` datdot-ui-plan-summary](https://github.com/playproject-io/datdot-ui/issues/66)
- [ ] [`datdot-ui#96` datdot-ui-mainsteps](https://github.com/playproject-io/datdot-ui/issues/96)

## Pages
- [ ] [`datdot-ui#22` screen: plan](https://github.com/playproject-io/datdot-ui/issues/22)
- [ ] [`datdot-ui#18` plan - add/edit - step: input title](https://github.com/playproject-io/datdot-ui/issues/18)
- [ ] [`datdot-ui#23` screen: user](https://github.com/playproject-io/datdot-ui/issues/22)
- [ ] [`datdot-ui#24` screen: work](https://github.com/playproject-io/datdot-ui/issues/22)
