### ISSUE TITLE
implement-plan-add/edit - step: swarm key

### ISSUE THREAD

**Issue by ninabreznik** [playproject-io/datdot-ui#196]
## `@todo`

---

```js
// widgets
require('datdot-ui-navigation')

// components
require('datdot-ui-plan-summary')
require('datdot-ui-mainsteps')
require('datdot-ui-search-autocomplete')
```

## Connection
- [ ] [`datdot-ui#46` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/46)
- [ ] #86
- [ ] #99
- [ ] [`datdot-ui#96` datdot-ui-mainsteps](https://github.com/playproject-io/datdot-ui/issues/96)

## Pages
* [ ] [`datdot-ui#22` screen: plan](https://github.com/playproject-io/datdot-ui/issues/22)
   - [ ] [`datdot-ui#18` plan - add/edit - step: input title](https://github.com/playproject-io/datdot-ui/issues/18)
   - [ ] [`datdot-ui#19` plan - add/edit - step: duration](https://github.com/playproject-io/datdot-ui/issues/19)
   - [ ] [`datdot-ui#21` plan - add/edit - step: data config - substep: select feeds & chunks](https://github.com/playproject-io/datdot-ui/issues/21)
* [ ] [`datdot-ui#23` screen: user](https://github.com/playproject-io/datdot-ui/issues/23)
* [ ] [`datdot-ui#24` screen: work](https://github.com/playproject-io/datdot-ui/issues/24)
