### ISSUE TITLE
implement-plan-add/edit - step: data config

### ISSUE THREAD

**Issue by ninabreznik** [playproject-io/datdot-ui#197]
## `@todo`

* [ ] components
  * [ ] #198
  * [ ] #199
  * [ ] #200
  * [ ] #201

---

```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-card')
require('datdot-ui-list')
require('datdot-ui-graphic')
require('datdot-ui-aciton')
require('datdot-ui-button')

// components
require('datdot-ui-plan-summary')
require('datdot-ui-mainsteps')

// other
require('data-cards-info')
require('estimated')
```

## Pages
* [ ] [`datdot-ui#22` screen: plan](https://github.com/playproject-io/datdot-ui/issues/22)
   - [ ] [`datdot-ui#18` plan - add/edit - step: input title](https://github.com/playproject-io/datdot-ui/issues/18)
   - [ ] [`datdot-ui#19` plan - add/edit - step: duration](https://github.com/playproject-io/datdot-ui/issues/19)
   - [ ] [`datdot-ui#20` plan - add/edit - step: swarm key](https://github.com/playproject-io/datdot-ui/issues/20)
   - [ ] [`datdot-ui#21` plan - add/edit - step: data config - substep: select feeds & chunks](https://github.com/playproject-io/datdot-ui/issues/21)
  - [ ] [`datdot-ui#16` plan - add/edit - step: publish](https://github.com/playproject-io/datdot-ui/issues/16)
* [ ] [`datdot-ui#23` screen: user](https://github.com/playproject-io/datdot-ui/issues/23)
* [ ] [`datdot-ui#24` screen: work](https://github.com/playproject-io/datdot-ui/issues/24)
