### ISSUE TITLE
ui-filter-option

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#2]
# Filter option
## @todo:
- [x] Data: Option list(Available, Not available, Hypercore, Hyperdrive, Cabal)
- [x] Add CSS style
- [x] Import datdot-ui-button
- [x] Toggle check function
- [ ] Testing string compare on Safari (with @serapath) 

#### Browsers testing (Laptop/Mobile/Tablet)
- [x] Chrome
- [x] Safari
- [x] Opera
- [ ] Edge (only laptop)
 
#### Device testing
 iPhone 6s Plus, iPad mini, simulator iPhone and iPad

---
## Issue repo
1. string compare failed in Safari
From data entry 
```js
let optionList = { unchecked: [], checked: ['Available', 'Not available', 'Hypercore', 'Hyperdrive', 'Cabal']}
```
Option button
```
const option = filterOption({page, flow, name: 'filter-option', data: optionList.checked}, optionProtocol('filter-option'))
```

```js
function optionProtocol (name) {
....
....
// get type 'unchecked' or 'checked' to check from and currentValue are equality.
if (type === 'unchecked') {
      // handle chekced status
      const result = optionList.checked.reduce( (acc, currentValue) => {
      if (from === currentValue) {
            const index = optionList.checked.indexOf(from)
            optionList.unchecked.push(from)
            optionList.checked.splice(index, 1)
      }
      acc = optionList.checked
      return acc
}, [])

if (type === 'checked') {
      // handle unchecked status
      const result = optionList.unchecked.reduce( (acc, currentValue) => {
      if (from === currentValue) {
            const index = optionList.unchecked.indexOf(from)
            optionList.checked.push(from)
            optionList.unchecked.splice(index, 1)
      }
      acc = optionList.checked
      return acc
}, [])
```

This code line is an issue to cause compare failed on Safari
```js
from === currentValue
```
#### Chrome result
![image](https://user-images.githubusercontent.com/9526525/103057926-d34b1680-45db-11eb-9106-9c0b79c0c2d1.png)
#### Safari result
![image](https://user-images.githubusercontent.com/9526525/103057919-cc240880-45db-11eb-8275-9ede53fe8d0f.png) ![image](https://user-images.githubusercontent.com/9526525/103057903-c4fcfa80-45db-11eb-99d0-06b045ea42fd.png)

Even I do console.log(typeof from, typeof currentValue)
This is what've I got
![image](https://user-images.githubusercontent.com/9526525/103058000-fd9cd400-45db-11eb-990e-ab1502e8cf20.png)

**Comment by serapath** [comment]
# Filter option
![image](https://user-images.githubusercontent.com/9526525/103095744-ac70fc80-463c-11eb-9cf7-5f29e95fdfbe.png)![image](https://user-images.githubusercontent.com/9526525/103058674-d3e4ac80-45dd-11eb-9ecd-6c4190977617.png)![image](https://user-images.githubusercontent.com/9526525/103095719-9a8f5980-463c-11eb-8e4a-a65761fb36a0.png)
