### ISSUE TITLE
[Design] Plan - Create new plan - swarm key

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#20]
# Swarm key
@todo design

### Update
v16
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v16/Tablet-Laptop-plans1-create%20new%20plan-step3%20data.png?raw=true)

---

### Issue report
Currently lack some informations about performance.
It may needs to improve UI later when see some informations need to remove or add.

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

#### v15-2
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-2/Tablet-Laptop-plans-create%20new%20plan-step3%20data.png?raw=true)

#### v15-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-1/Tablet-Laptop-plans-create%20new%20plan-step3%20data.png?raw=true)

#### v14
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v14/Tablet-Laptop-plans-create%20new%20plan-step3%20data.png?raw=true)

#### v13
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v13/Tablet-Laptop-plans-create%20new%20plan-step3%20data.png?raw=true)

#### v12-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v12-1/Tablet-Laptop-plans-create%20new%20plan-step3%20data-swarm%20key.png?raw=true)

#### v12
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v12/Tablet-Laptop-plans-create%20new%20plan-data%20subscribe-step3%20data%20-%20select%20swarm%20key.png?raw=true)

#### v8
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v8/Tablet-Laptop-plans-create%20new%20plan-search%20data-filters.png?raw=true)

#### v7
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v7/Tablet-Laptop-plans-default-feed%20status-options.png?raw=true)

#### v6
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v6/Tablet-Laptop-plans-default-feed%20status-options.png?raw=true)

#### v5
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v5/Tablet-Laptop-publish%20new%20data-add%20new%20range.png?raw=true)

#### v1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v1/Datdot%20app-hosting%20and%20service-hosting-fill%20info.png?raw=true)

**Comment by serapath** [comment]
# Swarm key
@todo design

### Update
v16
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v16/Tablet-Laptop-plans1-create%20new%20plan-step3%20data.png?raw=true)

---

### Issue report
Currently lack some informations about performance.
It may needs to improve UI later when see some informations need to remove or add.

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

#### v15-2
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-2/Tablet-Laptop-plans-create%20new%20plan-step3%20data.png?raw=true)

#### v15-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-1/Tablet-Laptop-plans-create%20new%20plan-step3%20data.png?raw=true)

#### v14
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v14/Tablet-Laptop-plans-create%20new%20plan-step3%20data.png?raw=true)

#### v13
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v13/Tablet-Laptop-plans-create%20new%20plan-step3%20data.png?raw=true)

#### v12-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v12-1/Tablet-Laptop-plans-create%20new%20plan-step3%20data-swarm%20key.png?raw=true)

#### v12
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v12/Tablet-Laptop-plans-create%20new%20plan-data%20subscribe-step3%20data%20-%20select%20swarm%20key.png?raw=true)

#### v8
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v8/Tablet-Laptop-plans-create%20new%20plan-search%20data-filters.png?raw=true)

#### v7
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v7/Tablet-Laptop-plans-default-feed%20status-options.png?raw=true)

#### v6
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v6/Tablet-Laptop-plans-default-feed%20status-options.png?raw=true)

#### v5
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v5/Tablet-Laptop-publish%20new%20data-add%20new%20range.png?raw=true)

#### v1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v1/Datdot%20app-hosting%20and%20service-hosting-fill%20info.png?raw=true)

**Comment by fionataeyang** [comment]
# Input title
```js
// widgets
require('datdot-ui-navigation')

// components
require('datdot-ui-plan-summary')
require('datdot-ui-mainsteps')
require('datdot-ui-search-autocomplete')
```

## Connection
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45)
- [ ] [`datdot-ui#66` datdot-ui-plan-summary](https://github.com/playproject-io/datdot-ui/issues/66)
- [ ] [`datdot-ui#4` datdot-ui-search-autocomplete](https://github.com/playproject-io/datdot-ui/issues/4)
- [ ] [`datdot-ui#96` datdot-ui-mainsteps](https://github.com/playproject-io/datdot-ui/issues/96)

## Pages
- [ ] [`datdot-ui#22` screen: plan](https://github.com/playproject-io/datdot-ui/issues/22)
- [ ] [`datdot-ui#18` plan - add/edit - step: input title](https://github.com/playproject-io/datdot-ui/issues/18)
- [ ] [`datdot-ui#19` plan - add/edit - step: duration](https://github.com/playproject-io/datdot-ui/issues/19)
- [ ] [`datdot-ui#23` screen: user](https://github.com/playproject-io/datdot-ui/issues/23)
- [ ] [`datdot-ui#24` screen: work](https://github.com/playproject-io/datdot-ui/issues/24)
