### ISSUE TITLE
implement-plan-add/edit - step: data config - substep: location

### ISSUE THREAD

**Issue by ninabreznik** [playproject-io/datdot-ui#200]
## `@todo`

---

```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-card')
require('datdot-ui-list')
require('datdot-ui-location-flags-tag')
require('datdot-ui-pin-map')

// components
require('datdot-ui-plan-summary')
require('datdot-ui-mainsteps')
require('datdot-ui-substeps')

// other
require('data-cards-info')
```

## Pages
* [ ] [`datdot-ui#22` screen: plan](https://github.com/playproject-io/datdot-ui/issues/22)
   - [ ] [`datdot-ui#18` plan - add/edit - step: input title](https://github.com/playproject-io/datdot-ui/issues/18)
   - [ ] [`datdot-ui#19` plan - add/edit - step: duration](https://github.com/playproject-io/datdot-ui/issues/19)
   - [ ] [`datdot-ui#20` plan - add/edit - step: swarm key](https://github.com/playproject-io/datdot-ui/issues/20)
   - [ ] [`datdot-ui#21` plan - add/edit - step: data config - substep: select feeds & chunks](https://github.com/playproject-io/datdot-ui/issues/21)
   - [ ] [`datdot-ui#44` plan - add/edit - step: data config - substep: schedule](https://github.com/playproject-io/datdot-ui/issues/44)
   - [ ] [`datdot-ui#117` plan - add/edit - step: data config - substep: performance](https://github.com/playproject-io/datdot-ui/issues/117)
* [ ] [`datdot-ui#23` screen: user](https://github.com/playproject-io/datdot-ui/issues/23)
* [ ] [`datdot-ui#24` screen: work](https://github.com/playproject-io/datdot-ui/issues/24)
