### ISSUE TITLE
[Design] Plan - Create new plan - select feeds & chunks

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#21]
# Select feeds & chunks
@todo design

### Update
v16
![image](https://user-images.githubusercontent.com/9526525/110213657-dfa4f700-7edb-11eb-9d04-078346203253.png)

---

### Issue report
Currently lack some informations about performance.
It may needs to improve UI later when see some informations need to remove or add.

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

#### v13
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v13/Tablet-Laptop-plans%E2%80%93create%20plan-select%20chunks4.png?raw=true)

#### v12-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v12-1/Tablet-Laptop-plans%E2%80%93create%20plan-selected%20chunks.png?raw=true)

#### v12
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v12/Tablet-Laptop-plans-create%20new%20plan-step4%20feeds%20-%20selected%20chunks.png?raw=true)

#### v10
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v10/Tablet-Laptop-plans-create%20new%20plan-select%20chunks.png?raw=true)

#### v8
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v8/Tablet-Laptop-plans-create%20new%20plan%20by%20cabal.png?raw=true)

#### v7
![image](https://user-images.githubusercontent.com/9526525/110214303-f3059180-7ede-11eb-9b29-4e94ad47babe.png)

#### v6
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v6/Tablet-Laptop-plans-create%20new%20plan-selected%20blocks.png?raw=true)

**Comment by serapath** [comment]
# Select feeds & chunks

### latest
v16
![image](https://user-images.githubusercontent.com/9526525/110213657-dfa4f700-7edb-11eb-9d04-078346203253.png)

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

#### v13
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v13/Tablet-Laptop-plans%E2%80%93create%20plan-select%20chunks4.png?raw=true)

#### v12-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v12-1/Tablet-Laptop-plans%E2%80%93create%20plan-selected%20chunks.png?raw=true)

#### v12
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v12/Tablet-Laptop-plans-create%20new%20plan-step4%20feeds%20-%20selected%20chunks.png?raw=true)

#### v10
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v10/Tablet-Laptop-plans-create%20new%20plan-select%20chunks.png?raw=true)

#### v8
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v8/Tablet-Laptop-plans-create%20new%20plan%20by%20cabal.png?raw=true)

#### v7
![image](https://user-images.githubusercontent.com/9526525/110214303-f3059180-7ede-11eb-9b29-4e94ad47babe.png)

#### v6
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v6/Tablet-Laptop-plans-create%20new%20plan-selected%20blocks.png?raw=true)

#### v5
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v5/Tablet-Laptop-publish%20new%20data-fill%20fileds.png?raw=true)

**Comment by fionataeyang** [comment]
# Feeds & chunks
```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-card')
require('datdot-ui-list')

// components
require('datdot-ui-plan-summary')
require('datdot-ui-mainsteps')

// other
require('data-cards-info')
```

## Connection
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45)
- [ ] [`datdot-ui#66` datdot-ui-plan-summary](https://github.com/playproject-io/datdot-ui/issues/66)
- [ ] [`datdot-ui#86` datdot-ui-card](https://github.com/playproject-io/datdot-ui/issues/86)
- [ ] [`datdot-ui#72` datdot-ui-list](https://github.com/playproject-io/datdot-ui/issues/72)
- [ ] [`datdot-ui#96` datdot-ui-mainsteps](https://github.com/playproject-io/datdot-ui/issues/96)

## Pages
- [ ] [`datdot-ui#22` screen: plan](https://github.com/playproject-io/datdot-ui/issues/22)
- [ ] [`datdot-ui#19` plan - add/edit - step: duration](https://github.com/playproject-io/datdot-ui/issues/19)
- [ ] [`datdot-ui#23` screen: user](https://github.com/playproject-io/datdot-ui/issues/23)
- [ ] [`datdot-ui#24` screen: work](https://github.com/playproject-io/datdot-ui/issues/24)
