### ISSUE TITLE
plan screen

### ISSUE THREAD

**Issue by serapath** [playproject-io/datdot-ui#22]
## `@todo`
* [ ]
* [ ]

---

**Comment by serapath** [comment]
# Plan

### latest
v16
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v16/Tablet-Laptop-plans1.png?raw=true)

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

#### v15-3
Plans1 layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-3/Tablet-Laptop-plans1.png?raw=true)

#### v15-2
Plans1 layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-2/Tablet-Laptop-plans1.png?raw=true)

Plans layout
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-2/Tablet-Laptop-plans.png?raw=true)

#### v15-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-1/Tablet-Laptop-plans.png?raw=true)

#### v13-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v13-1/Tablet-Laptop-plans.png?raw=true)

#### v12
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v12/Tablet-Laptop-plans.png?raw=true)

#### v8
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v8/Tablet-Laptop-plans-default.png?raw=true)

#### v7
![image](https://raw.githubusercontent.com/fionataeyang/datdot-ui/master/design/datdot-app-v7/Tablet-Laptop-plans-default.png)

#### v6
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v6/Tablet-Laptop-plans-default.png?raw=true)

#### v5
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v5/Tablet-Laptop-data-no%20data.png?raw=true)

#### v4
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v4/Tablet-Laptop-feeds-no%20data.png?raw=true)

#### v0
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v0/Datdot%20app-dashboard-empty.png?raw=true)

**Comment by fionataeyang** [comment]
# Default
```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-action')
require('datdot-ui-button')
require('datdot-ui-graphic')
require('datdot-ui-tooltip')

// components
require('datdot-ui-custom-action-bar')
```

- [ ] [`datdot-ui#3` datdot-ui-button](https://github.com/playproject-io/datdot-ui/issues/3)
- [ ] [`datdot-ui#10` datdot-ui-graphic](https://github.com/playproject-io/datdot-ui/issues/10) 
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45)
- [ ] [`datdot-ui#46` datdot-ui-action](https://github.com/playproject-io/datdot-ui/issues/46)
- [ ] [`datdot-ui#54` datdot-ui-custom-action-bar](https://github.com/playproject-io/datdot-ui/issues/54)
- [ ] [`datdot-ui#68` datdot-ui-tooltip](https://github.com/playproject-io/datdot-ui/issues/68)
- [ ] [`datdot-ui#23` SCREEN: user](https://github.com/playproject-io/datdot-ui/issues/23)
- [ ] [`datdot-ui#24` SCREEN: work](https://github.com/playproject-io/datdot-ui/issues/24)
