### ISSUE TITLE
user screen

### ISSUE THREAD

**Issue by serapath** [playproject-io/datdot-ui#23]
# `@todo`
* [ ] make user screen

---

**Comment by fionataeyang** [comment]
# Dashboard

### latest
#### v7
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-USER-v7/USER-default.png?raw=true)

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.
#### v6
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-USER-v6/USER-default.png?raw=true)

#### v3
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-USER-v3/USER-default.png?raw=true)

#### v1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-USER-v1/USER-default.png?raw=true)

**Comment by fionataeyang** [comment]
# Default
```js
require('datdot-ui-navigation')
require('datdot-ui-action')
```
## Connection
- [ ] [`datdot-ui#46` datdot-ui-action](https://github.com/playproject-io/datdot-ui/issues/46)
- [ ] [`datdot-ui#45` datdot-ui-action](https://github.com/playproject-io/datdot-ui/issues/45)
