### ISSUE TITLE
plan - add/edit - step: data config

### ISSUE THREAD

**Issue by serapath** [playproject-io/datdot-ui#27]
## `@todo`
  * [ ] when no "data card" is selected, maybe we should try to move the big (+) button to add a new card into the action bar?
  * [x] while filling out the add card wizard form - even when coming to the `"data config step"` intially:
    * [x] always show `"card box summary info"` (including price)
    * [x] highlight the part of the "summary info" of the "card box" which summarizes the current sub step
      * [x] with a "focus color"
  * [x] add colors for specific use and i would recommend:
    * [x] 1. warning color (to make user pay attention to certain problems)
       * see https://youtu.be/BUmwevSH_VU?t=105
    * [x] 2. focus color (to mark specific parts of the app to highlight where a user is and what the user is doing - e.g. during filling out wizard steps)
        * see https://youtu.be/qO3JLZyJcNY?t=55
        * another example can be seen in VS CODE with the "high contrast theme"
            * file explorer position ===> active tab ===> minimap ===> linenumber+ line ===> cursor
            * see https://imgur.com/UuRb40e.png
            * we could use: plan creation ===> wizard step bubble ==> data card field ==> current form input
                * ...or something like that :-)
---

**Comment by fionataeyang** [comment]
#  Data config
### latest
#### v18-4
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v18-4/Plans-new%20plan-step4-data%20config-data%20cards%20multiple%20selected.png?raw=true)

---

### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

#### v18-3
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v18-3/Plans-new%20plan-step4-data%20config-data%20cards%20multiple%20selected.png?raw=true)

#### v18-3
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v18-3/Plans-new%20plan-step4-data%20config-data%20cards%20multiple%20selected.png?raw=true)

#### v18-2
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v18-2/Plans-new%20plan-step4-data%20config-data%20cards%20multiple%20selected.png?raw=true)

#### v18
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v18/Plans-new%20plan-step4-data%20config-data%20cards%20multiple%20selected.png?raw=true)

#### v16
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v16/Tablet-Laptop-plans1-create%20new%20plan-step3-data%20config-cards%20added-multiple%20selected.png?raw=true)

#### v15-1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-1/Tablet-Laptop-plans-create%20new%20plan-step3-data%20config-cards%20added.png?raw=true)
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15-1/Tablet-Laptop-plans-create-new-plan-step4-publish-select%20card.png?raw=true)

#### v15
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v15/Tablet-Laptop-plans-create-new-plan-step4-publish-add%20new%20card-data-select%20chunks%20%E2%80%93%201.png?raw=true)

**Comment by fionataeyang** [comment]
# Data config
```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-card')
require('datdot-ui-list')
require('datdot-ui-graphic')
require('datdot-ui-aciton')
require('datdot-ui-button')

// components
require('datdot-ui-plan-summary')
require('datdot-ui-mainsteps')

// other
require('data-cards-info')
require('estimated')
```

## Connection
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45)
- [ ] [`datdot-ui#66` datdot-ui-plan-summary](https://github.com/playproject-io/datdot-ui/issues/66)
- [ ] [`datdot-ui#86` datdot-ui-card](https://github.com/playproject-io/datdot-ui/issues/86)
- [ ] [`datdot-ui#72` datdot-ui-list](https://github.com/playproject-io/datdot-ui/issues/72)
- [ ] [`datdot-ui#96` datdot-ui-mainsteps](https://github.com/playproject-io/datdot-ui/issues/96)
- [ ] [`datdot-ui#3` datdot-ui-button](https://github.com/playproject-io/datdot-ui/issues/3)
- [ ] [`datdot-ui#10` datdot-ui-graphic](https://github.com/playproject-io/datdot-ui/issues/10)
- [ ] [`datdot-ui#46` datdot-ui-action](https://github.com/playproject-io/datdot-ui/issues/46)

## Pages
- [ ] [`datdot-ui#22` screen: plan](https://github.com/playproject-io/datdot-ui/issues/22)
- [ ] [`datdot-ui#18` plan - add/edit - step: input title](https://github.com/playproject-io/datdot-ui/issues/18)
- [ ] [`datdot-ui#19` plan - add/edit - step: duration](https://github.com/playproject-io/datdot-ui/issues/19)
- [ ] [`datdot-ui#20` plan - add/edit - step: swarm key](https://github.com/playproject-io/datdot-ui/issues/20)
- [ ] [`datdot-ui#21` plan - add/edit - step: data config - substep: select feeds & chunks](https://github.com/playproject-io/datdot-ui/issues/21)
- [ ] [`datdot-ui#16` plan - add/edit - step: publish](https://github.com/playproject-io/datdot-ui/issues/16)
- [ ] [`datdot-ui#23` screen: user](https://github.com/playproject-io/datdot-ui/issues/23)
- [ ] [`datdot-ui#24` screen: work](https://github.com/playproject-io/datdot-ui/issues/24)
