### ISSUE TITLE
plan - add/edit - step: data config - substep: regions

### ISSUE THREAD

**Issue by serapath** [playproject-io/datdot-ui#28]
## `@todo`
* [ ] allow to select multiple locations/regions to be selected

---

**Comment by fionataeyang** [comment]
# Latest
v18-2
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v18-2/5/Plans-new%20plan-step4-data%20config-location.png?raw=true)

**Comment by fionataeyang** [comment]
# Schedule

```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-card')
require('datdot-ui-list')
require('datdot-ui-location-flags-tag')
require('datdot-ui-pin-map')

// components
require('datdot-ui-plan-summary')
require('datdot-ui-mainsteps')
require('datdot-ui-substeps')

// other
require('data-cards-info')
```

## Connection
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45)
- [ ] [`datdot-ui#66` datdot-ui-plan-summary](https://github.com/playproject-io/datdot-ui/issues/66)
- [ ] [`datdot-ui#86` datdot-ui-card](https://github.com/playproject-io/datdot-ui/issues/86)
- [ ] [`datdot-ui#72` datdot-ui-list](https://github.com/playproject-io/datdot-ui/issues/72)
- [ ] [`datdot-ui#96` datdot-ui-mainsteps](https://github.com/playproject-io/datdot-ui/issues/96)
- [ ] [`datdot-ui#97` datdot-ui-substeps](https://github.com/playproject-io/datdot-ui/issues/97)
- [ ] [`datdot-ui#93` datdot-ui-pin-map](https://github.com/playproject-io/datdot-ui/issues/93)
- [ ] [`datdot-ui#101` datdot-ui-location-flag-tag](https://github.com/playproject-io/datdot-ui/issues/101)

## Pages
- [ ] [`datdot-ui#22` screen: plan](https://github.com/playproject-io/datdot-ui/issues/22)
- [ ] [`datdot-ui#18` plan - add/edit - step: input title](https://github.com/playproject-io/datdot-ui/issues/18)
- [ ] [`datdot-ui#19` plan - add/edit - step: duration](https://github.com/playproject-io/datdot-ui/issues/19)
- [ ] [`datdot-ui#20` plan - add/edit - step: swarm key](https://github.com/playproject-io/datdot-ui/issues/20)
- [ ] [`datdot-ui#21` plan - add/edit - step: data config - substep: select feeds & chunks](https://github.com/playproject-io/datdot-ui/issues/44)
- [ ] [`datdot-ui#44` plan - add/edit - step: schedule](https://github.com/playproject-io/datdot-ui/issues/44)
- [ ] [`datdot-ui#23` screen: user](https://github.com/playproject-io/datdot-ui/issues/23)
- [ ] [`datdot-ui#24` screen: work](https://github.com/playproject-io/datdot-ui/issues/24)
