### ISSUE TITLE
notifications/help overlay box

### ISSUE THREAD

**Issue by serapath** [playproject-io/datdot-ui#29]
## `@todo`
* [ ] design notifications overlay box
* [ ] design help overlay box
* [ ] implement notifcations/help overlay box component

---

**Comment by serapath** [comment]
![notifications1](https://user-images.githubusercontent.com/1771897/110267916-aa220b80-7fb8-11eb-8f89-b91f5b92b450.jpeg)
---
![helpnotification](https://user-images.githubusercontent.com/1771897/110267919-aabaa200-7fb8-11eb-93c8-45b9a1f7b98d.jpeg)

**Comment by fionataeyang** [comment]
# Help mode
### Plan summary list
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v18-2/5/Plans-help%20mode-plan%20list.png?raw=true)

### Map
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v18-2/5/Plans-help%20mode-map.png?raw=true)

### Map
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v18-2/5/Plans-help%20mode-chart.png?raw=true)

### actions
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v18-2/5/Plans-help%20mode-actions.png?raw=true)
