### ISSUE TITLE
[UI] Button

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#3]
# Button
![image](https://user-images.githubusercontent.com/9526525/103065449-912ccf80-45f1-11eb-958f-47d866d100b7.png)
## @todo:
- [x] Button demo (example: text, icon, link, disabled, toggle, switch, navigation)
- [x] Add CSS style
- [x] Add custom css

#### Browsers testing (Laptop/Mobile/Tablet)
- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Opera
- [ ] Edge (only laptop)

#### Device testing
* iPhone 6s Plus, iPad mini, simulator iPhone and iPad
* Maybe will use simulator with Android

**Comment by serapath** [comment]
# Button
![image](https://user-images.githubusercontent.com/9526525/103065449-912ccf80-45f1-11eb-958f-47d866d100b7.png)

**Comment by serapath** [comment]
> @ninabreznik 
> [**worklog `2022.04.07` - locking UI elements**](https://youtu.be/X8wpMNnAW2E) 

Notes:
- v.0.0.1-alpha: ui elements, updated to use new comm protocol
- 0.0.0-alpha: ui elements in the original Fiona's state (only a few)
- tab component has since moved into button component (under tab is old version, under button is many types of buttons, including the tab). When we start refactoring (splitting/merging components), we can see what to do here. I made a comment in the issues:
* #8


### Results:
**v0.0.1-alpha** (using new comm proto)
- https://github.com/datdot-ui/button/tree/v0.0.1-alpha

**0.0.0-alpha** (old/Fiona's original)
- https://github.com/datdot-ui/button/tree/0.0.0-alpha

**Comment by serapath** [comment]
> @ninabreznik 
> [**worklog `2022.04.12` - versioning and documenting components**](https://youtu.be/gCKEtJ2eG8o)

**results:**

- `v0.0.1-alpha`
  - https://github.com/datdot-ui/button/tree/v0.0.1-alpha
- `v0.0.0-prealpha`
    - https://github.com/datdot-ui/button/tree/v0.0.0-prealpha
-  `v0.0.0-alpha` 
    - https://github.com/datdot-ui/button/tree/v0.0.0-alpha
- updated readme
    - https://github.com/datdot-ui/button#datdot-ui-button
