### ISSUE TITLE
user - add new account - create new account

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#32]
## `@todo`
* [ ] finish design
* [ ] start implementing

**Comment by fionataeyang** [comment]
# Create new account

### latest
v2
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-USER-v2/USER-create%20new%20account.png?raw=true)

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

**Comment by fionataeyang** [comment]
```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-input-text')
require('datdot-ui-label')
require('datdot-ui-title')
require('datdot-ui-user-avatar')

// components
require('datdot-ui-modal')
require('datdot-ui-mainsteps')
```
## Connection
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45)
- [ ] [`datdot-ui#67` datdot-ui-modal](https://github.com/playproject-io/datdot-ui/issues/67)
- [ ] [`datdot-ui#77` datdot-ui-input-text](https://github.com/playproject-io/datdot-ui/issues/77)
- [ ] [`datdot-ui#96` datdot-ui-mainsteps](https://github.com/playproject-io/datdot-ui/issues/96)
- [ ] [`datdot-ui#90` datdot-ui-user-avatar](https://github.com/playproject-io/datdot-ui/issues/90)
