### ISSUE TITLE
user - add new account - import account

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#33]
## `@todo`
* [ ] finish design
* [ ] start implementing

**Comment by fionataeyang** [comment]
# Import account

### latest
v2
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-USER-v2/USER-import%20account.png?raw=true)

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

**Comment by fionataeyang** [comment]
```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-input-text')
require('datdot-ui-input-textarea')
require('datdot-ui-label')
require('datdot-ui-title')
require('datdot-ui-user-avatar')

// components
require('datdot-ui-modal')
require('datdot-ui-mainsteps')

// modal content
require('header')
require('body')
```
## Connection
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45)
- [ ] [`datdot-ui#67` datdot-ui-modal](https://github.com/playproject-io/datdot-ui/issues/67)
- [ ] [`datdot-ui#84` datdot-ui-title](https://github.com/playproject-io/datdot-ui/issues/84)
- [ ] [`datdot-ui#77` datdot-ui-input-text](https://github.com/playproject-io/datdot-ui/issues/77)
- [ ] [`datdot-ui#79` datdot-ui-textarea](https://github.com/playproject-io/datdot-ui/issues/79)
- [ ] [`datdot-ui#78` datdot-ui-label](https://github.com/playproject-io/datdot-ui/issues/78)
- [ ] [`datdot-ui#90` datdot-ui-user-avatar](https://github.com/playproject-io/datdot-ui/issues/90)
- [ ] [`datdot-ui#96` datdot-ui-mainsteps](https://github.com/playproject-io/datdot-ui/issues/96)

## Pages
- [ ] [`datdot-ui#23` screen: user](https://github.com/playproject-io/datdot-ui/issues/23)
- [ ] [`datdot-ui#37` user - import account - account information](https://github.com/playproject-io/datdot-ui/issues/37)
