### ISSUE TITLE
user - add new account - seed phrase

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#34]
## `@todo`
* [ ] finish design
* [ ] start implementing

**Comment by fionataeyang** [comment]
# Duration

### latest
v2
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-USER-v2/USER-create%20new%20account-seed%20phrase.png?raw=true)

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

**Comment by fionataeyang** [comment]
```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-title')
require('datdot-ui-button')
require('datdot-ui-notify')

// components
require('datdot-ui-modal')
require('datdot-ui-mainsteps')

// modal content
require('header')
require('body')
```
## Connection
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45)
- [ ] [`datdot-ui#96` datdot-ui-mainsteps](https://github.com/playproject-io/datdot-ui/issues/96)
- [ ] [`datdot-ui#67` datdot-ui-modal](https://github.com/playproject-io/datdot-ui/issues/67)
- [ ] [`datdot-ui#84` datdot-ui-title](https://github.com/playproject-io/datdot-ui/issues/84)
- [ ] [`datdot-ui#83` datdot-ui-notify](https://github.com/playproject-io/datdot-ui/issues/83)
- [ ] [`datdot-ui#3` datdot-ui-button](https://github.com/playproject-io/datdot-ui/issues/3)

## Pages
- [ ] [`datdot-ui#23` screen: user](https://github.com/playproject-io/datdot-ui/issues/23)
- [ ] [`datdot-ui#32` user - add new account - create new account](https://github.com/playproject-io/datdot-ui/issues/32)
- [ ] [`datdot-ui#36` user - add new account - create new account - proof seed phrase](https://github.com/playproject-io/datdot-ui/issues/36)
