### ISSUE TITLE
user - add new account - option

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#35]
## `@todo`
* [ ] finish design
* [ ] start implementing

**Comment by fionataeyang** [comment]
# Add new account by option
### latest
#### v3
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-USER-v3/USER-add%20account-option.png?raw=true)

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

#### v2
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-USER-v2/USER-add%20account-option.png?raw=true)

**Comment by fionataeyang** [comment]
```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-action')
require('datdot-ui-button')
require('datdot-ui-graphic')
```
## Connection
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45)
- [ ] [`datdot-ui#46` datdot-ui-action](https://github.com/playproject-io/datdot-ui/issues/46)
- [ ] [`datdot-ui#3` datdot-ui-button](https://github.com/playproject-io/datdot-ui/issues/3)
- [ ] [`datdot-ui#10` datdot-ui-graphic](https://github.com/playproject-io/datdot-ui/issues/10)

## Pages
- [ ] [`datdot-ui#23` screen: user](https://github.com/playproject-io/datdot-ui/issues/23)
- [ ] [`#32` create new account](https://github.com/playproject-io/datdot-ui/issues/32)
- [ ] [`datdot-ui#33` user - import account](https://github.com/playproject-io/datdot-ui/issues/33)
