### ISSUE TITLE
user - activity (transactions)

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#39]
## `@todo`
* [ ] finish design
* [ ] start implementing

**Comment by fionataeyang** [comment]
# Transactions activity

### latest
#### v5
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-USER-v5/USER-activity-sort.png?raw=true)

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

#### v4
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-USER-v4/USER-activity-sort.png?raw=true)

#### v3
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-USER-v3/USER-activity-sort.png?raw=true)

#### v2
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-USER-v2/USER-activity-sort.png?raw=true)

**Comment by fionataeyang** [comment]
```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-action')
require('datdot-ui-button')
require('datdot-ui-graphic')
require('datdot-ui-tooltip')
require('datdot-ui-activity')
require('datdot-ui-list')
require('datdot-ui-title')
require('datdot-ui-filter')

// components
require('datdot-ui-custom-action-bar')
require('datdot-ui-modal')
```

// modal content
require('header')
require('body')

## Call actions
- [ ] [`datdot-ui#35` user - add new account - option](https://github.com/playproject-io/datdot-ui/issues/35)
- [ ] [`datdot-ui#38` user - switch account](https://github.com/playproject-io/datdot-ui/issues/38)
- [ ] [`datdot-ui#42` user - switch account - enter password](https://github.com/playproject-io/datdot-ui/issues/42)
- [ ] [`datdot-ui#40` user - edit account](https://github.com/playproject-io/datdot-ui/issues/40)
- [ ] [`datdot-ui#116` user - remove account](https://github.com/playproject-io/datdot-ui/issues/116)
- [ ] [`datdot-ui#41` user - transfer](https://github.com/playproject-io/datdot-ui/issues/41)
- [ ] [`datdot-ui#55` datdot-ui-sort](https://github.com/playproject-io/datdot-ui/issues/55)
- [ ] [`datdot-ui#53` datdot-ui-filter](https://github.com/playproject-io/datdot-ui/issues/53)
- [ ] [`datdot-ui#54` datdot-ui-custom-action-bar](https://github.com/playproject-io/datdot-ui/issues/54)
- [ ] [`datdot-ui#29` notifications/help overlay box](https://github.com/playproject-io/datdot-ui/issues/29)
