### ISSUE TITLE
[UI] search autocomplete

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#4]
# Search autocomplete
![image](https://user-images.githubusercontent.com/9526525/103066216-5d52a980-45f3-11eb-938a-300f1f8e8037.png)

## @todo:
- [x] Search input
- [x] Search input filter result
- [x] Filter result
- [x] Get feeds length
- [x] Select swarm
- [x] Import datdot-ui-filter-option  and datdot-ui-button
- [x] Add CSS style
- [ ] Filter result from option's dropdown(Available/Not available/Hypercore/Hyperdrive/Cabal)
- [x] Address type valid (current use http://)
- [x] Error style (when address is not valid)

#### Browsers testing (Laptop/Mobile/Tablet)
- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Opera
- [ ] Edge (only laptop)

#### Device testing
* iPhone 6s Plus, iPad mini, simulator iPhone and iPad
* Maybe will use simulator with Android
---
## Issue report
1. current issue is same as [ui-filter-option](https://github.com/playproject-io/datdot-ui/issues/2) #2

**Comment by serapath** [comment]
# Search autocomplete
![image](https://user-images.githubusercontent.com/9526525/103066216-5d52a980-45f3-11eb-938a-300f1f8e8037.png)

**Comment by fionataeyang** [comment]
![image](https://user-images.githubusercontent.com/9526525/117007347-1fd9f780-ad1c-11eb-9e74-6d2a1e983493.png)
