### ISSUE TITLE
plan - add/edit - sub step: schedule

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#44]
## `@todo`
* [ ] finish design
* [ ] start implementing

**Comment by fionataeyang** [comment]
# Schedule

```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-card')
require('datdot-ui-list')
require('datdot-ui-input-text')
require('datdot-ui-label')
require('datdot-ui-action')

// components
require('datdot-ui-plan-summary')
require('datdot-ui-mainsteps')
require('datdot-ui-substeps')
require('datdot-ui-schedule')

// other
require('data-cards-info')
```

## Connection
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45)
- [ ] [`datdot-ui#66` datdot-ui-plan-summary](https://github.com/playproject-io/datdot-ui/issues/66)
- [ ] [`datdot-ui#86` datdot-ui-card](https://github.com/playproject-io/datdot-ui/issues/86)
- [ ] [`datdot-ui#72` datdot-ui-list](https://github.com/playproject-io/datdot-ui/issues/72)
- [ ] [`datdot-ui#96` datdot-ui-mainsteps](https://github.com/playproject-io/datdot-ui/issues/96)
- [ ] [`datdot-ui#97` datdot-ui-substeps](https://github.com/playproject-io/datdot-ui/issues/97)
- [ ] [`datdot-ui#76` datdot-ui-schedule](https://github.com/playproject-io/datdot-ui/issues/76)
- [ ] [`datdot-ui#77` datdot-ui-input-text](https://github.com/playproject-io/datdot-ui/issues/76)
- [ ] [`datdot-ui#78` datdot-ui-label](https://github.com/playproject-io/datdot-ui/issues/76)
- [ ] [`datdot-ui#46` datdot-ui-action](https://github.com/playproject-io/datdot-ui/issues/46)

## Pages
- [ ] [`datdot-ui#22` screen: plan](https://github.com/playproject-io/datdot-ui/issues/22)
- [ ] [`datdot-ui#18` plan - add/edit - step: input title](https://github.com/playproject-io/datdot-ui/issues/18)
- [ ] [`datdot-ui#19` plan - add/edit - step: duration](https://github.com/playproject-io/datdot-ui/issues/19)
- [ ] [`datdot-ui#20` plan - add/edit - step: swarm key](https://github.com/playproject-io/datdot-ui/issues/20)
- [ ] [`datdot-ui#21` plan - add/edit - step: data config - substep: select feeds & chunks](https://github.com/playproject-io/datdot-ui/issues/44)
- [ ] [`datdot-ui#23` screen: user](https://github.com/playproject-io/datdot-ui/issues/23)
- [ ] [`datdot-ui#24` screen: work](https://github.com/playproject-io/datdot-ui/issues/24)
