### ISSUE TITLE
[UI] Custom action bar

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#54]
### Custom action bar
![image](https://user-images.githubusercontent.com/9526525/116714098-f95c4980-aa07-11eb-8536-4f8bd59041da.png)

#### Add action
![image](https://user-images.githubusercontent.com/9526525/116714392-51934b80-aa08-11eb-8834-3386b1c86da7.png)
![image](https://user-images.githubusercontent.com/9526525/116714576-7f789000-aa08-11eb-8b3d-14e848d71aa8.png)

#### Display or hide
![image](https://user-images.githubusercontent.com/9526525/116714724-a3d46c80-aa08-11eb-87ae-606fd54f0bea.png)

#### Remove action
![image](https://user-images.githubusercontent.com/9526525/116714177-0f6a0a00-aa08-11eb-8eec-d0feede49d06.png) 
![image](https://user-images.githubusercontent.com/9526525/116714303-33c5e680-aa08-11eb-8232-b7b1e782554a.png)

**Comment by fionataeyang** [comment]
```js
// datdot-ui-custom-action-bar
require('datdot-ui-button')
require('datdot-ui-graphic')
require('datdot-ui-checkbox')
require('datdot-ui-action')
```
## Connection
- [ ] [`datdot-ui#3` datdot-ui-button](https://github.com/playproject-io/datdot-ui/issues/3)
- [ ] [`datdot-ui#10` datdot-ui-graphic](https://github.com/playproject-io/datdot-ui/issues/10)#23 
- [ ] [`datdot-ui#46` datdot-ui-action](https://github.com/playproject-io/datdot-ui/issues/46)
```
