### ISSUE TITLE
jobs - dashboard 

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#57]
## `@todo`
* [ ] finish design
* [ ] start implementing

**Comment by fionataeyang** [comment]
### latest
#### v5
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v5/JOBS-information-line%20chart%20&%20bar%20chart.png?raw=true)

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.
#### v4
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v4/JOBS-information%20-%20line%20chart%20&%20pie%20chart.png?raw=true)
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v4/JOBS-information-line%20chart%20&%20bar%20chart.png?raw=true)

#### v3
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v3/JOBS-information.png?raw=true)

#### v2
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v2/JOBS-information.png?raw=true)

#### v1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v1/JOBS-information.png?raw=true)

#### v0
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v0/Tablet-Laptop-jobs-hosting.png?raw=true)
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v0/Tablet-Laptop-jobs-calendar.png?raw=true)

**Comment by fionataeyang** [comment]
# Default
```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-action')
require('datdot-ui-button')
require('datdot-ui-graphic')
require('datdot-ui-tooltip')
require('datdot-ui-list')
require('datdot-ui-activity')
require('datdot-ui-chart-legend')
require('datdot-ui-linechart')
require('datdot-ui-barchart)
require('datdot-ui-piechart')
require('datdot-ui-chart-scalebar')
require('datdot-ui-title')
require('datdot-ui-card')

// components
require('datdot-ui-custom-action-bar')
require('datdot-ui-modal')

// call actions
require('settings-resources')
```

## Connection
- [ ] [`datdot-ui#3` datdot-ui-button](https://github.com/playproject-io/datdot-ui/issues/3)
- [ ] [`datdot-ui#10` datdot-ui-graphic](https://github.com/playproject-io/datdot-ui/issues/10) 
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45)
- [ ] [`datdot-ui#46` datdot-ui-action](https://github.com/playproject-io/datdot-ui/issues/46)
- [ ] [`datdot-ui#54` datdot-ui-custom-action-bar](https://github.com/playproject-io/datdot-ui/issues/54)
- [ ] [`datdot-ui#67` datdot-ui-modal](https://github.com/playproject-io/datdot-ui/issues/54)
- [ ] [`datdot-ui#68` datdot-ui-tooltip](https://github.com/playproject-io/datdot-ui/issues/68)
- [ ] [`datdot-ui#69` datdot-ui-linechart](https://github.com/playproject-io/datdot-ui/issues/69)
- [ ] [`datdot-ui#111` datdot-ui-barchart](https://github.com/playproject-io/datdot-ui/issues/111)
- [ ] [`datdot-ui#112` datdot-ui-piechart](https://github.com/playproject-io/datdot-ui/issues/112)
- [ ] [`datdot-ui#114` datdot-ui-chart-scalebar](https://github.com/playproject-io/datdot-ui/issues/114)
- [ ] [`datdot-ui#72` datdot-ui-list](https://github.com/playproject-io/datdot-ui/issues/72)
- [ ] [`datdot-ui#104` datdot-ui-list](https://github.com/playproject-io/datdot-ui/issues/104)
- [ ] [`datdot-ui#84` datdot-ui-title](https://github.com/playproject-io/datdot-ui/issues/84)
- [ ] [`datdot-ui#86` datdot-ui-card](https://github.com/playproject-io/datdot-ui/issues/86)
