### ISSUE TITLE
jobs - activity

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#58]
# Activity
#### v5
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v5/JOBS-activity-sort.png?raw=true)

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.
#### v2
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v2/JOBS-activity-sort.png?raw=true)

#### v0
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v0/Tablet-Laptop-jobs-hosting.png?raw=true)

**Comment by fionataeyang** [comment]
# Dashboard
```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-action')
require('datdot-ui-button')
require('datdot-ui-graphic')
require('datdot-ui-tooltip')
require('datdot-ui-list')
require('datdot-ui-activity')
require('datdot-ui-card')
require('datdot-ui-search')
require('datdot-ui-sort')
require('datdot-ui-filter')
require('datdot-ui-piechart')

// components
require('datdot-ui-custom-action-bar')
require('datdot-ui-modal')

// call actions
require('settings-resources')
```

## Connection
- [ ] [`datdot-ui#3` datdot-ui-button](https://github.com/playproject-io/datdot-ui/issues/3)
- [ ] [`datdot-ui#10` datdot-ui-graphic](https://github.com/playproject-io/datdot-ui/issues/10) 
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45)
- [ ] [`datdot-ui#46` datdot-ui-action](https://github.com/playproject-io/datdot-ui/issues/46)
- [ ] [`datdot-ui#54` datdot-ui-custom-action-bar](https://github.com/playproject-io/datdot-ui/issues/54)
- [ ] [`datdot-ui#67` datdot-ui-modal](https://github.com/playproject-io/datdot-ui/issues/54)
- [ ] [`datdot-ui#68` datdot-ui-tooltip](https://github.com/playproject-io/datdot-ui/issues/68)
- [ ] [`datdot-ui#72` datdot-ui-list](https://github.com/playproject-io/datdot-ui/issues/72)
- [ ] [`datdot-ui#104` datdot-ui-activity](https://github.com/playproject-io/datdot-ui/issues/104)
- [ ] [`datdot-ui#112` datdot-ui-piechart](https://github.com/playproject-io/datdot-ui/issues/112)
- [ ] [`datdot-ui#84` datdot-ui-title](https://github.com/playproject-io/datdot-ui/issues/84)
- [ ] [`datdot-ui#86` datdot-ui-card](https://github.com/playproject-io/datdot-ui/issues/86)
- [ ] [`datdot-ui#99` datdot-ui-search](https://github.com/playproject-io/datdot-ui/issues/99)
- [ ] [`datdot-ui#55` datdot-ui-sort](https://github.com/playproject-io/datdot-ui/issues/55)
- [ ] [`datdot-ui#53` datdot-ui-filter](https://github.com/playproject-io/datdot-ui/issues/53)

**Comment by ninabreznik** [comment]
# Activity
```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-action')
require('datdot-ui-button')
require('datdot-ui-graphic')
require('datdot-ui-tooltip')
require('datdot-ui-list')
require('datdot-ui-activity')
require('datdot-ui-card')
require('datdot-ui-search')
require('datdot-ui-sort')
require('datdot-ui-filter')
require('datdot-ui-piechart')
require('datdot-ui-title')

// components
require('datdot-ui-custom-action-bar')
require('datdot-ui-modal')

// call actions
require('settings-resources')
```
## Pages
- [ ] [`datdot-ui#32` user - create new account](https://github.com/playproject-io/datdot-ui/issues/32)
- [ ] [`datdot-ui#59` work - settings - step: resources](https://github.com/playproject-io/datdot-ui/issues/59)
- [ ] [`datdot-ui#57` work - dashboard](https://github.com/playproject-io/datdot-ui/issues/57)
- [ ] [`datdot-ui#22` SCREEN: plan](https://github.com/playproject-io/datdot-ui/issues/22)
- [ ] [`datdot-ui#23` SCREEN: user](https://github.com/playproject-io/datdot-ui/issues/23)

## Call actions
- [ ] [`datdot-ui#35` user - add new account - option](https://github.com/playproject-io/datdot-ui/issues/35)
- [ ] [`datdot-ui#38` user - switch account](https://github.com/playproject-io/datdot-ui/issues/38)
- [ ] [`datdot-ui#42` user - switch account - enter password](https://github.com/playproject-io/datdot-ui/issues/42)
- [ ] [`datdot-ui#40` user - edit account](https://github.com/playproject-io/datdot-ui/issues/40)
- [ ] [`datdot-ui#116` user - remove account](https://github.com/playproject-io/datdot-ui/issues/116)
- [ ] [`datdot-ui#41` user - transfer](https://github.com/playproject-io/datdot-ui/issues/41)
- [ ] [`datdot-ui#55` datdot-ui-sort](https://github.com/playproject-io/datdot-ui/issues/55)
- [ ] [`datdot-ui#53` datdot-ui-filter](https://github.com/playproject-io/datdot-ui/issues/53)
- [ ] [`datdot-ui#54` datdot-ui-custom-action-bar](https://github.com/playproject-io/datdot-ui/issues/54)
- [ ] [`datdot-ui#29` notifications/help overlay box](https://github.com/playproject-io/datdot-ui/issues/29)
