### ISSUE TITLE
jobs  - settings - step: resources

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#59]
## `@todo`
* [ ] finish design
* [ ] start implementing

**Comment by fionataeyang** [comment]
# Schedule

### latest
#### v3
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v3/JOBS-settings-resources.png?raw=true)

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

#### v2
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v2/JOBS-settings-resources.png?raw=true)

#### v1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v1/JOBS-settings-resources.png?raw=true)

**Comment by fionataeyang** [comment]
```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-input-text')
require('datdot-ui-slider-range')
require('datdot-ui-label')
require('datdot-ui-title')

// components
require('datdot-ui-modal')
require('datdot-ui-mainsteps')

// modal content
require('header')
require('body')

## Connection
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45
- [ ] [`datdot-ui#96` datdot-ui-mainsteps](https://github.com/playproject-io/datdot-ui/issues/96)
- [ ] [`datdot-ui#106` datdot-ui-slider-range](https://github.com/playproject-io/datdot-ui/issues/106) 
- [ ] [`datdot-ui#77` datdot-ui-input-text](https://github.com/playproject-io/datdot-ui/issues/77)
- [ ] [`datdot-ui#78` datdot-ui-label](https://github.com/playproject-io/datdot-ui/issues/78) 
- [ ] [`datdot-ui#84` datdot-ui-title](https://github.com/playproject-io/datdot-ui/issues/84) 
- [ ] [`datdot-ui#67` datdot-ui-modal](https://github.com/playproject-io/datdot-ui/issues/67)
