### ISSUE TITLE
jobs - settings - step: resources

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#60]
## `@todo`
* [ ] finish design
* [ ] start implementing

**Comment by fionataeyang** [comment]
# Reward

### latest
#### v3
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v3/JOBS-settings-reward.png?raw=true)

#### add
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v3/JOBS-settings-reward-add.png?raw=true)

#### delete
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v3/JOBS-settings-reward-delete.png?raw=true)

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.

#### v2
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v2/JOBS-settings-reward.png?raw=true)

**Comment by fionataeyang** [comment]
```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-input-number')
require('datdot-ui-slider-range')
require('datdot-ui-label')
require('datdot-ui-title')
require('datdot-ui-account-selector')

// components
require('datdot-ui-modal')
require('datdot-ui-mainsteps')

// modal content
require('body')
```

## Connection
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45)
- [ ] [`datdot-ui#96` datdot-ui-mainsteps](https://github.com/playproject-io/datdot-ui/issues/96)
- [ ] [`datdot-ui#106` datdot-ui-slider-range](https://github.com/playproject-io/datdot-ui/issues/106) 
- [ ] [`datdot-ui#77` datdot-ui-input-number](https://github.com/playproject-io/datdot-ui/issues/77)
- [ ] [`datdot-ui#78` datdot-ui-label](https://github.com/playproject-io/datdot-ui/issues/78) 
- [ ] [`datdot-ui#84` datdot-ui-title](https://github.com/playproject-io/datdot-ui/issues/84) 
- [ ] [`datdot-ui#67` datdot-ui-modal](https://github.com/playproject-io/datdot-ui/issues/67) 
- [ ] [`datdot-ui#105` datdot-ui-account-selector](https://github.com/playproject-io/datdot-ui/issues/105) 

## Pages
- [ ] [`datdot-ui#24` SCREEN: work](https://github.com/playproject-io/datdot-ui/issues/24)
- [ ] [`datdot-ui#59` jobs - settings - step: resources](https://github.com/playproject-io/datdot-ui/issues/59)
