### ISSUE TITLE
jobs - settings - step: location

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#61]
## `@todo`
* [ ] finish design
* [ ] start implementing

**Comment by fionataeyang** [comment]
# Location

### latest
#### v4
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v4/JOBS-settings-location.png?raw=true)

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.
#### v3
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v3/JOBS-settings-location.png?raw=true)

#### v2
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v2/JOBS-settings-location.png?raw=true)

**Comment by fionataeyang** [comment]
```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-geohash-map')
require('datdot-ui-search')

// components
require('datdot-ui-mainsteps')
```

## Connection
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45)
- [ ] [`datdot-ui#96` datdot-ui-mainsteps](https://github.com/playproject-io/datdot-ui/issues/96)
- [ ] [`datdot-ui#94` datdot-ui-geohash-map](https://github.com/playproject-io/datdot-ui/issues/94)
- [ ] [`datdot-ui#99` datdot-ui-search](https://github.com/playproject-io/datdot-ui/issues/99)

## Pages
- [ ] [`datdot-ui#23` SCREEN: user](https://github.com/playproject-io/datdot-ui/issues/23)
- [ ] [`datdot-ui#22` SCREEN: plan](https://github.com/playproject-io/datdot-ui/issues/22)
- [ ] [`datdot-ui#24` SCREEN: work](https://github.com/playproject-io/datdot-ui/issues/24)
- [ ] [`datdot-ui#59` jobs - settings - step: resources](https://github.com/playproject-io/datdot-ui/issues/59)
- [ ] [`datdot-ui#60` jobs - settings - step: reward](https://github.com/playproject-io/datdot-ui/issues/60)
