### ISSUE TITLE
jobs - settings - step: schedule

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#62]
## `@todo`
* [ ] finish design
* [ ] start implementing

**Comment by fionataeyang** [comment]
# Schedule

### latest
#### v4
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v4/JOBS-settings-schedule.png?raw=true)

---
### Previous design
This is comparing with update design when we need to discuss, and also track the progress to follow up new design.
#### v3
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v3/JOBS-settings-schedule.png?raw=true)

#### v2
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v2/JOBS-settings-schedule.png?raw=true)

#### v1
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v1/JOBS-settings-schedule.png?raw=true)

#### v0
Add
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v0/Tablet-Laptop-jobs-set%20new%20limits-wizard%20step3.png?raw=true)
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v0/Tablet-Laptop-jobs-set%20new%20limits-wizard%20step4.png?raw=true)

Edit
![image](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-JOBS-v0/Tablet-Laptop-jobs-eidt%20limits-schedule.png?raw=true)

**Comment by fionataeyang** [comment]
```js
// widgets
require('datdot-ui-navigation')
require('datdot-ui-input-text')
require('datdot-ui-label')

// components
require('datdot-ui-mainsteps')
require('datdot-ui-schedule')
```

## Connection
- [ ] [`datdot-ui#45` datdot-ui-navigation](https://github.com/playproject-io/datdot-ui/issues/45)
- [ ] [`datdot-ui#96` datdot-ui-mainsteps](https://github.com/playproject-io/datdot-ui/issues/96)
- [ ] [`datdot-ui#78` datdot-ui-label](https://github.com/playproject-io/datdot-ui/issues/78)
- [ ] [`datdot-ui#77` datdot-ui-input-text](https://github.com/playproject-io/datdot-ui/issues/77)
