### ISSUE TITLE
[UI] Dropdown

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#71]
## `@todo`
* [x] implement first iteration of component
  * [x] create repository
  * [x] set up local dev environment with **pnpm**
    * [x] pnpm link the modules locally
      * [x] `pnpm link --global` (to make them available)
      * [x] `pnpm link --global <./package.json#name>`
  * `@output` :package: [`repository`](https://github.com/datdot-ui/dropdown/tree/a7aef50232849139e142088fadde3199c15622ab)
* [x] refactor component for last Fiona's commit and tag it with `v0.0.0-alpha`
  * `@input` :package: [`repository`](https://github.com/datdot-ui/dropdown/tree/a7aef50232849139e142088fadde3199c15622ab)
  * [x] refactor commit with latest terminal/log to use versions
  * [x] move terminal/logs to dev dependencies
  * [x] rebase main branch on top of taged version
  * [x] update package.json (new path for the dependencies)
  * [ ] `@output` :package: [`v0.0.0-alpha`](https://github.com/datdot-ui/dropdown/tree/v0.0.0-alpha)
* [x] refactor component latest commit with new comm protocol and tag with `v0.0.1.-alpha`
  * [ ] `@input` :package: [`v0.0.0-alpha`](https://github.com/datdot-ui/dropdown/tree/v0.0.0-alpha)
  * [x] refactor latest commit with latest terminal/log to use versions
  * [x] refactor communication protocol to use latest message standard
  * [x] move terminal/logs to dev dependencies
  * [x] rebase main branch on top of taged version
  * [x] update package.json (new path for the dependencies)
  * [x] update github page links
  * [x] build new bundle.js to include changes in demo page[
  * `@output` :package: [`v0.0.1-alpha`](https://github.com/datdot-ui/dropdown/tree/v0.0.1-alpha)
* [ ] refactor component latest commit with new comm protocol and tag with v0.0.3-alpha
  * `@input` :package: [`v0.0.2-alpha`](https://github.com/datdot-ui/checkbox/tree/v0.0.2-alpha)
  * [ ] set up github page using demo maker component dev dependency
  * `@output` :question: `repository#v0.0.3-alpha`
* [ ] implement next component version `v0.0.4-alpha`
  * `@input` :package: [`v0.0.3-alpha`](https://github.com/datdot-ui/dropdown/tree/v0.0.3-alpha)
  * [ ] fix bugs & add features for v0.0.4
    * [ ] Refactor codes(protocol, receive, recipients)
    * [ ] refactor all `messages` and `status` and update documentation
  * [ ] set up github page using demo maker component dev dependency
  * [ ] document component api in readme or whatever needs to show in the readme
    * [ ] document apis for each screen and return available actions
      * `@input` :question: `wireframes action bars`
  * [ ] document component api in readme
    * [x] list all `opts`
    * [x] list all `roles`
    * [x] list all `incoming message types`
    * [x] list all `outgoing message types`
    * [ ] list all possible `status` the component instance can be in
    * `@output` :factory: [README.md](https://github.com/datdot-ui/dropdown/blob/ac9f41d837513595850859247d932421f7d45503/README.md)
  * [ ] install latest dev dependencies
    * [ ] budo
    * [ ] browserify
    * [ ] datdot-terminal
  * [ ] install latest specific version of dependencies
    * [ ] #3
  * [ ] update github page links
  * [ ] build new bundle.js to include changes in demo page
  * [ ] update package.json (new path for the dependencies)
  * `@input` :question: `repository#v0.0.4-alpha`

---

### Repo :open_file_folder:
https://github.com/datdotorg/datdot-ui-dropdown

### Notes
- Layout mode
- Selector view
  - Custom select element for `<select></select>` html tag
- Filter view
  - Custom `︙` icon button for `<button>` html tag

### for account
![image](https://user-images.githubusercontent.com/9526525/117842774-d60b8700-b2b0-11eb-8127-f80acae27f4d.png)
![image](https://user-images.githubusercontent.com/9526525/117842757-d2780000-b2b0-11eb-9d0e-010ac06c033f.png)

### for chain network
![image](https://user-images.githubusercontent.com/9526525/117842963-fdfaea80-b2b0-11eb-8810-bf2b28adcbf9.png)

### for duration
![image](https://user-images.githubusercontent.com/9526525/117843206-34d10080-b2b1-11eb-93e1-337cb3f0814e.png)

### for feeds
![image](https://user-images.githubusercontent.com/9526525/118285348-ec5d5100-b503-11eb-810a-1a61c04445e6.png)

### for date range
![image](https://user-images.githubusercontent.com/9526525/117851532-fd665200-b2b8-11eb-9cba-2a351dc1747b.png)

![image](https://user-images.githubusercontent.com/9526525/117851463-f0496300-b2b8-11eb-8725-baa502af8401.png)
![image](https://user-images.githubusercontent.com/9526525/117851493-f5a6ad80-b2b8-11eb-9d7f-9f08510aa3f4.png)

**Comment by serapath** [comment]
> @ninabreznik 
> [**worklog `2022.04.07` - locking UI elements**](https://youtu.be/X8wpMNnAW2E) 

Notes:
- v.0.0.1-alpha: ui elements, updated to use new comm protocol

### Results:
**v0.0.1-alpha** (using new comm proto)
- https://github.com/datdot-ui/dropdown/tree/v0.0.1-alpha

**Comment by serapath** [comment]
> @ninabreznik 
> [**worklog `2022.04.12` - versioning and documenting components**](https://youtu.be/gCKEtJ2eG8o)

**results:**

- `v0.0.1-alpha`
  - https://github.com/datdot-ui/dropdown/tree/v0.0.1-alpha
-  `v0.0.0-alpha` 
  - https://github.com/datdot-ui/dropdown/tree/v0.0.0-alpha
- updated readme
  - https://github.com/datdot-ui/dropdown#datdot-ui-dropdown
