### ISSUE TITLE
[UI] Calendar

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#76]
## `@todo`
* `@input` :factory: #7 
* `@input` :question: dates selected - from - to
* [ ] make datdot-ui-set-time component
* [ ] make datdot-ui-set-repeat component
* [ ] make datdot-ui-custom-days component
* `@output` :factory: `v0.0.2-alpha`

---

## `@info`

```js
// datdot-ui-schedule
require('datdot-ui-datepicker')
require('datdot-ui-set-time')
require('datdot-ui-set-repeat')
require('datdot-ui-custom-days')
```

### Schedule
![image](https://user-images.githubusercontent.com/9526525/117847712-2f75b500-b2b5-11eb-8ec9-570b82f93d45.png)

https://github.com/playproject-io/datdot-ui
