### ISSUE TITLE
[UI] Tab

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#8]
# Tab
![image](https://user-images.githubusercontent.com/9526525/103095352-48016d80-463b-11eb-8db8-27ac0686a0e2.png)

## @todo:
- [x] Tab demo
- [x] Add CSS style
- [ ] Import domlog
- [ ] Import #3 datdot-ui-button
- [ ] Refactor codes(protocol, receive, recipients

#### Browsers testing (Laptop/Mobile/Tablet)
- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Opera
- [ ] Edge (only laptop)

#### Device testing
* iPhone 6s Plus, iPad mini, simulator iPhone and iPad
* Maybe will use simulator with Android
---
## Issue report

**Comment by serapath** [comment]
# Tab
![image](https://user-images.githubusercontent.com/9526525/103095352-48016d80-463b-11eb-8db8-27ac0686a0e2.png)

**Comment by fionataeyang** [comment]
![image](https://user-images.githubusercontent.com/9526525/117995872-416a5d00-b374-11eb-9dc3-a80a078e353e.png)

![image](https://user-images.githubusercontent.com/9526525/117995922-4af3c500-b374-11eb-89e2-7024dff7e0af.png)

![image](https://user-images.githubusercontent.com/9526525/117995991-59da7780-b374-11eb-9160-e02cabe21783.png)

![image](https://user-images.githubusercontent.com/9526525/117996025-6068ef00-b374-11eb-8435-2d1ed8c344da.png)

**Comment by serapath** [comment]
> @ninabreznik 
> [**worklog `2022.04.07` - locking UI elements**](https://youtu.be/X8wpMNnAW2E) 

- tab component has since moved into button component (under tab is old version, under button is many types of buttons, including the tab). When we start refactoring (splitting/merging components), we can see what to do here. I made a comment in the issues:
* #3
