### ISSUE TITLE
[UI] Day selector - range

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#81]
## `@todo`
* [x] implement first iteration of component
  * [x] create repository
  * [x] set up local dev environment with **pnpm**
    * [x] pnpm link the modules locally
      * [x] `pnpm link --global` (to make them available)
      * [x] `pnpm link --global <./package.json#name>`
  * `@output` :factory: `repository`
* [x] refactor component for last Fiona's commit and tag it with `v0.0.0-alpha`
  * `@input` :factory: `repository`
  * [x] refactor commit with latest terminal/log to use versions
  * [x] move terminal/logs to dev dependencies
  * [x] rebase main branch on top of taged version
  * [x] update package.json (new path for the dependencies)
  * `@output` :factory: [`v0.0.0-alpha`](https://github.com/datdot-ui/calendar-days/releases/tag/v0.0.0-alpha)
* [x] refactor component latest commit with new comm protocol and tag with `v0.0.1-alpha`
  * `@input` :factory: [`v0.0.0-alpha`](https://github.com/datdot-ui/calendar-days/releases/tag/v0.0.0-alpha)
  * [x] refactor latest commit with latest terminal/log to use versions
  * [x] refactor communication protocol to use latest message standard
  * [x] move terminal/logs to dev dependencies
  * [x] rebase main branch on top of taged version
  * [x] update package.json (new path for the dependencies)
  * [x] update github page links
  * [x] build new bundle.js to include changes in demo page
  * `@output` :factory: [`v0.0.1-alpha`](https://github.com/datdot-ui/calendar-days/releases/tag/v0.0.1-alpha)
* [x] implement next component version `v0.0.4-alpha`
  * `@input` :factory: [`v0.0.1-alpha`](https://github.com/datdot-ui/calendar-days/releases/tag/v0.0.1-alpha)
  * [x] fix bugs & add features for v0.0.2
    * [x] select range between two calendars
    * [x] clear all when click outside of calendar
    * [x] clear all when both selected and next month clicked  
    * [x] freeze next month when certain calendar selected (keep prev and next working on other calendar)
  * [x] document component api in readme
    * [x] list all `opts`
    * [x] list all `incoming message types`
    * [x] list all `outgoing message types`
  * [x] install latest dependencies
    * [x] budo
    * [x] browserify
  * [x] install latest specific version of dependencies
  * [x] build new bundle.js to include changes in demo page
  * [x] update package.json (new path for the dependencies)
  * `@output` :factory: [`v0.0.4-alpha`](https://github.com/datdot-ui/calendar-days/releases/tag/v0.0.4-alpha)
---

## `@info`

https://github.com/datdot-ui/range-picker-days

```js
// datdot-ui-calendar-dates
require('datdot-ui-button')
```
### Calendar dates
![image](https://user-images.githubusercontent.com/9526525/117851191-a6f91380-b2b8-11eb-96f9-0c3c04fe8d1e.png)
