### ISSUE TITLE
[UI] Template

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#9]
# Template
![image](https://user-images.githubusercontent.com/9526525/103095956-53559880-463d-11eb-90dc-5158ef6164b2.png)

## @todo:
- [x] App layout demo
- [x] Add CSS style
- [ ] Create new plan
- [ ] USER page
- [ ] PLANS page
- [ ] JOBS page
- [ ] APPs page
- [ ] Import domlog
- [ ] Import #3 datdot-ui-button
- [ ] Import #4 datdot-ui-autocomplete
- [ ] Import #5 datdot-ui-datepicker
- [ ] Import #8 datdot-ui-tab
- [ ] Refactor codes(protocol, receive, recipients

#### Browsers testing (Laptop/Mobile/Tablet)
- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Opera
- [ ] Edge (only laptop)

#### Device testing
* iPhone 6s Plus, iPad mini, simulator iPhone and iPad
* Maybe will use simulator with Android
---
## Issue report

**Comment by serapath** [comment]
* [ ] put all components into `src/node_modules/<component-name>/**/*`
* [ ] make demo pages for components under `examples/<component-name>/index.html`
  * [ ] import components via `const component = require('datdot-ui/node_modules/<component-name>')`
* [ ] make datdot-ui `examples/index.html` into a styleguide page to showcase all components

---
for latest versions, check: https://github.com/fionataeyang/datdot-ui

## designs
1. **plan list collapsed**
     1. [plans list - empty](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v10/Tablet-Laptop-plans-default.png)
     * [plans list - empty colored](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v13/Tablet-Laptop-plans.png)
     * [plans list - indicator - select active](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v10/Tablet-Laptop-plans-plan-data%20info-stop%20plan.png)
     * [plans list - indicator - select inactive](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v10/Tablet-Laptop-plans-plan-data%20info-stop%20plan-button%20inactive.png)
     * [plans list - colord new button active](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v12/Tablet-Laptop-plans-plan-data%20info-stop%20plan%20%E2%80%93%201.png)
     * [plans list - colord new button inactive](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v12/Tablet-Laptop-plans-plan-data%20info-stop%20plan-button%20inactive.png)
2. **plan list expanded**
    1. [plan list - all with notifications](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v6/Tablet-Laptop-data-grid%20view.png)
    * [plan list - with activities](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v6/Tablet-Laptop-data-multiple%20select.png)
    * [plan list - activity item details](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v6/Tablet-Laptop-data-published%20info.png)
2. **popup overlay**
    1. [start sponsor plan](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v10/Tablet-Laptop-plans-list-subscribe%20plan.png)
    * [stop1 sponser plan](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v10/Tablet-Laptop-plans-list-stop%20plan.png)
    * [stop2 sponsor plan](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v8/Tablet-Laptop-plans-list-remove%20and%20stop%20plan.png)
3. **activity feed**
    * [activity feed](https://github.com/fionataeyang/datdot-ui/blob/master/design/datdot-app-v6/Tablet-Laptop-data-publisher-block%20info.png)

**Comment by serapath** [comment]
### Summary by @fiona

- https://github.com/playproject-io/datdot-ui/issues/119#issuecomment-885779061
- https://github.com/playproject-io/datdot-ui/issues/119#issuecomment-894799125

**Comment by ninabreznik** [comment]
- [ ] BOTTOM MENU
![Screenshot_2022-08-26_00-12-03](https://user-images.githubusercontent.com/1076427/186784490-e5c291b1-4afd-4f76-8e47-88c61362d320.png)

  - [ ] menu buttons
![Screenshot_2022-08-26_00-09-24](https://user-images.githubusercontent.com/1076427/186784254-43217b56-1e07-4501-a5a2-bdfed4134e24.png)
  - [ ] action tab 
![Screenshot_2022-08-26_00-10-39](https://user-images.githubusercontent.com/1076427/186784361-c70199a5-5770-4fb3-b2d0-c344d8f0e032.png)
![Screenshot_2022-08-26_00-16-31](https://user-images.githubusercontent.com/1076427/186784866-5b41f9e8-2230-42b2-a53f-013d437ffc29.png)
  - [ ] subaction tab
![Screenshot_2022-08-26_00-19-04](https://user-images.githubusercontent.com/1076427/186785149-6a5fc5b4-e3cc-410b-8fdb-a080138cdfc1.png)
  - [ ] steps
![Screenshot_2022-08-26_00-20-39](https://user-images.githubusercontent.com/1076427/186785231-d420bfeb-0b72-41d9-82da-ca77b662e698.png)
![Screenshot_2022-08-26_00-22-08](https://user-images.githubusercontent.com/1076427/186785456-061d8cc2-9e68-4887-8e5f-abb567d45d88.png)
  - [ ] substeps
![Screenshot_2022-08-26_00-14-16](https://user-images.githubusercontent.com/1076427/186784677-b842215e-48b6-467d-b313-baa096744840.png)

- [ ] USER
  - [ ] create account form
  
![Screenshot_2022-08-26_01-43-46](https://user-images.githubusercontent.com/1076427/186792838-ceeaa8d7-035c-432c-91b5-f9beccec3efd.png)

**Comment by ninabreznik** [comment]
- [ ] navigation
  - [ ] menu buttons
  - [ ] action bar
  - [ ] steps
  - [ ] substeps
- [ ] inputs
  - [ ] dropdown
  - [ ] password
  - [ ] button
  - [ ] toggle
  - [ ] checkbox
  - [ ] input text
  - [ ] input integer
  - [ ] input date
  - [ ] input time
  - [ ] input autocomplete (tags/countries/cities)
  - [ ] range slider
- [ ] stats
  - [ ] graph
  - [ ] percentage boxes
  - [ ] legend
- [ ] map
  - [ ] location flag map
