### ISSUE TITLE
[UI] Steps (progress bar)

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#96]
## `@todo`
* [ ] create repository
  * `@output` :question: `repository`
* [ ] implement first iteration of component and tag with `v0.0.1-alpha`
  * `@input` :question: `repository`
  * [ ] update package.json (new path for the dependencies and version `v0.0.1-alpha`)
  * [ ] install budo and browserify as dev dependency
  * [ ] add terminal to dev dependencies
  * [ ] set up github page using demo maker component dev dependency
  * [ ] implement first version and add communication protocol and use latest message standard
  * [ ] build new bundle.js to include changes in demo page
  * [ ] document component api in readme or whatever needs to show in the readme
    * [ ] document apis for each screen and return available actions
      * `@input` :question: `wireframes action bars`
    * [ ] list all `opts`
    * [ ] list all `roles`
    * [ ] list all `incoming message types`
    * [ ] list all `outgoing message types`
    * [ ] list all possible `status` the component instance can be in
    * `@output` :question: `repo#readme.md`
  * [ ] install latest specific version of dependencies
    * [ ] #3
    * [ ] #10
    * [ ] make datdot-ui-steps component
  * `@output` :question: `repo_url#v0.0.1-alpha`

---

## `@info`

```js
// datdot-ui-mainsteps
require('datdot-ui-steps')
require('datdot-ui-button')
require('datdot-ui-graphic')
```

##### User
![image](https://user-images.githubusercontent.com/9526525/117998124-2c8ec900-b376-11eb-9d10-650da76c1ba4.png)

##### Plan
![image](https://user-images.githubusercontent.com/9526525/117998013-1254eb00-b376-11eb-83e6-af27a4215cef.png)

#####  Job
![image](https://user-images.githubusercontent.com/9526525/117998260-4c25f180-b376-11eb-882c-f3d7e24f6bed.png)

### Sub steps
![image](https://user-images.githubusercontent.com/9526525/117999424-690ef480-b377-11eb-9f02-4aa140efa0ce.png)
