### ISSUE TITLE
[UI] Search

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/datdot-ui#99]
# Search
![image](https://user-images.githubusercontent.com/9526525/118001762-9b215600-b379-11eb-8136-c1abddb38622.png)

![image](https://user-images.githubusercontent.com/9526525/118001804-a5dbeb00-b379-11eb-8c4a-4f6faae2161a.png)

```js
// datdot-ui-search
require('datdot-ui-input-text')
require('datdot-ui-button')
require('datdot-ui-graphic')
```

## Connection
- [ ] [`datdot-ui#3` datdot-ui-button](https://github.com/playproject-io/datdot-ui/issues/3)
- [ ] [`datdot-ui#10` datdot-ui-graphic](https://github.com/playproject-io/datdot-ui/issues/10)
- [ ] [`datdot-ui#77` datdot-ui-inpu](https://github.com/playproject-io/datdot-ui/issues/10)

**Comment by serapath** [comment]
> @ninabreznik 
> [**worklog `2022.04.07` - locking UI elements**](https://youtu.be/X8wpMNnAW2E) 

Notes:
- v.0.0.1-alpha: ui elements, updated to use new comm protocol
- 0.0.0-alpha: ui elements in the original Fiona's state (only a few)

### Results:
**0.0.0-alpha** (old/Fiona's original)
- https://github.com/datdot-ui/search-autocomplete/tree/0.0.0-alpha

**Comment by serapath** [comment]
> @ninabreznik 
> [**worklog `2022.04.12` - versioning and documenting components**](https://youtu.be/gCKEtJ2eG8o)

**results:**

- `v0.0.0-prealpha`
    - https://github.com/datdot-ui/search-autocomplete/tree/v0.0.0-prealpha
    
- updated readme
    - https://github.com/datdot-ui/search-autocomplete
